import { calculateDate } from '@shared/business/utilities/DateHandler';

// eslint-disable-next-line complexity
export function toKyselyNewDocketEntry(docketEntry: RawDocketEntry) {
  return {
    action: docketEntry.action ?? null,
    additionalInfo: docketEntry.additionalInfo ?? null,
    additionalInfo2: docketEntry.additionalInfo2 ?? null,
    addToCoversheet: docketEntry.addToCoversheet ?? null,
    archived: docketEntry.archived ?? null,
    attachments: docketEntry.attachments ?? null,
    caseType: docketEntry.caseType ?? null,
    certificateOfService: docketEntry.certificateOfService ?? null,
    certificateOfServiceDate: docketEntry.certificateOfServiceDate
      ? calculateDate({ dateString: docketEntry.certificateOfServiceDate })
      : null,
    createdAt: calculateDate({ dateString: docketEntry.createdAt }),
    date: docketEntry.date
      ? calculateDate({ dateString: docketEntry.date })
      : null,
    docketEntryId: docketEntry.docketEntryId,
    docketNumber: docketEntry.docketNumber,
    docketNumbers: docketEntry.docketNumbers ?? null,
    documentContentsId: docketEntry.documentContentsId ?? null,
    documentIdBeforeSignature: docketEntry.documentIdBeforeSignature ?? null,
    documentTitle: docketEntry.documentTitle,
    documentType: docketEntry.documentType ?? null,
    draftOrderState: JSON.stringify(docketEntry.draftOrderState) ?? null,
    editState: docketEntry.editState ?? null,
    eventCode: docketEntry.eventCode,
    filedBy: docketEntry.filedBy ?? null,
    filedByRole: docketEntry.filedByRole ?? null,
    filers: docketEntry.filers,
    filingDate: calculateDate({ dateString: docketEntry.filingDate }),
    freeText: docketEntry.freeText ?? null,
    hasOtherFilingParty: docketEntry.hasOtherFilingParty ?? null,
    hasSupportingDocuments: docketEntry.hasSupportingDocuments ?? null,
    index: docketEntry.index ?? null,
    isAutoGenerated: docketEntry.isAutoGenerated ?? null,
    isDraft: docketEntry.isDraft ?? null,
    isFileAttached: docketEntry.isFileAttached ?? null,
    isLegacy: docketEntry.isLegacy ?? null,
    isLegacySealed: docketEntry.isLegacySealed ?? null,
    isOnDocketRecord: docketEntry.isOnDocketRecord,
    isPaper: docketEntry.isPaper ?? null,
    isPendingService: docketEntry.isPendingService ?? null,
    isSealed: docketEntry.isSealed === undefined ? false : docketEntry.isSealed,
    isStricken: docketEntry.isStricken ?? null,
    judge: docketEntry.judge ?? null,
    lodged: docketEntry.lodged ?? null,
    mailingDate: docketEntry.mailingDate ?? null,
    noticeIssuedDate: docketEntry.noticeIssuedDate
      ? calculateDate({ dateString: docketEntry.noticeIssuedDate })
      : null,
    numberOfPages: docketEntry.numberOfPages ?? null,
    objections: docketEntry.objections ?? null,
    ordinalValue: docketEntry.ordinalValue ?? null,
    otherFilingParty: docketEntry.otherFilingParty ?? null,
    otherIteration: docketEntry.otherIteration ?? null,
    partyIrsPractitioner: docketEntry.partyIrsPractitioner ?? null,
    pending: docketEntry.pending ?? null,
    previousDocument: JSON.stringify(docketEntry.previousDocument) ?? null,
    privatePractitioners:
      JSON.stringify(docketEntry.privatePractitioners) ?? null,
    processingStatus: docketEntry.processingStatus,
    qcAt: docketEntry.qcAt
      ? calculateDate({ dateString: docketEntry.qcAt })
      : null,
    qcByUserId: docketEntry.qcByUserId ?? null,
    receivedAt: calculateDate({ dateString: docketEntry.receivedAt }),
    redactionAcknowledgement: docketEntry.redactionAcknowledgement ?? null,
    relationship: docketEntry.relationship ?? null,
    scenario: docketEntry.scenario ?? null,
    sealedTo: docketEntry.sealedTo,
    secondaryDocument: JSON.stringify(docketEntry.secondaryDocument) ?? null,
    servedAt: docketEntry.servedAt
      ? calculateDate({ dateString: docketEntry.servedAt })
      : null,
    servedParties: JSON.stringify(docketEntry.servedParties) ?? null,
    servedPartiesCode: docketEntry.servedPartiesCode ?? null,
    serviceDate: docketEntry.serviceDate
      ? calculateDate({ dateString: docketEntry.serviceDate })
      : null,
    serviceStamp: docketEntry.serviceStamp ?? null,
    signedAt: docketEntry.signedAt
      ? calculateDate({ dateString: docketEntry.signedAt })
      : null,
    signedByUserId: docketEntry.signedByUserId ?? null,
    signedJudgeName: docketEntry.signedJudgeName ?? null,
    signedJudgeUserId: docketEntry.signedJudgeUserId ?? null,
    stampData: JSON.stringify(docketEntry.stampData) ?? null,
    strickenAt: docketEntry.strickenAt
      ? calculateDate({ dateString: docketEntry.strickenAt })
      : null,
    strickenBy: docketEntry.strickenBy ?? null,
    strickenByUserId: docketEntry.strickenByUserId ?? null,
    supportingDocument: docketEntry.supportingDocument ?? null,
    taxYear: docketEntry.taxYear ?? null,
    trialLocation: docketEntry.trialLocation ?? null,
    userId: docketEntry.userId ?? null,
  };
}
