import { DocketEntry } from '@shared/business/entities/DocketEntry';
import { calculateDate } from '@shared/business/utilities/DateHandler';
import { DatabaseSchema } from '@web-api/database-schema';
import { NewDocketEntryKysely } from '@web-api/persistence/postgres/docketEntries/schema';
import { DatabaseToAppCodeMapper } from '@web-api/persistence/postgres/utils/databaseToAppCodeMapper';

// eslint-disable-next-line complexity
export function toKyselyNewDocketEntry(
  docketEntry: RawDocketEntry,
): NewDocketEntryKysely {
  return {
    action: docketEntry.action ?? null,
    additionalInfo: docketEntry.additionalInfo ?? null,
    additionalInfo2: docketEntry.additionalInfo2 ?? null,
    addToCoversheet: docketEntry.addToCoversheet ?? null,
    archived: docketEntry.archived ?? null,
    attachments: docketEntry.attachments ?? null,
    caseType: docketEntry.caseType ?? null,
    certificateOfService: docketEntry.certificateOfService ?? null,
    certificateOfServiceDate: docketEntry.certificateOfServiceDate
      ? calculateDate({ dateString: docketEntry.certificateOfServiceDate })
      : null,
    createdAt: calculateDate({ dateString: docketEntry.createdAt }),
    date: docketEntry.date
      ? calculateDate({ dateString: docketEntry.date })
      : null,
    docketEntryId: docketEntry.docketEntryId,
    docketNumber: docketEntry.docketNumber,
    docketNumbers: docketEntry.docketNumbers ?? null,
    documentContentsId: docketEntry.documentContentsId ?? null,
    documentIdBeforeSignature: docketEntry.documentIdBeforeSignature ?? null,
    documentTitle: docketEntry.documentTitle,
    documentType: docketEntry.documentType ?? null,
    draftOrderState: docketEntry.draftOrderState
      ? JSON.stringify(docketEntry.draftOrderState)
      : null,
    editState: docketEntry.editState ?? null,
    eventCode: docketEntry.eventCode,
    filedBy: docketEntry.filedBy ?? null,
    filedByRole: docketEntry.filedByRole ?? null,
    filers: JSON.stringify(docketEntry.filers),
    filingDate: calculateDate({ dateString: docketEntry.filingDate }),
    freeText: docketEntry.freeText ?? null,
    hasOtherFilingParty: docketEntry.hasOtherFilingParty ?? null,
    hasSupportingDocuments: docketEntry.hasSupportingDocuments ?? null,
    index: docketEntry.index ?? null,
    isAutoGenerated: docketEntry.isAutoGenerated ?? null,
    isDraft: docketEntry.isDraft ?? null,
    isFileAttached: docketEntry.isFileAttached ?? null,
    isLegacy: docketEntry.isLegacy ?? null,
    isLegacySealed: docketEntry.isLegacySealed ?? null,
    isLegacyServed: docketEntry.isLegacyServed ?? false,
    isOnDocketRecord: docketEntry.isOnDocketRecord,
    isPaper: docketEntry.isPaper ?? null,
    isPendingService: docketEntry.isPendingService ?? null,
    isSealed: docketEntry.isSealed === undefined ? false : docketEntry.isSealed,
    isStricken: docketEntry.isStricken ?? null,
    judge: docketEntry.judge ?? null,
    lodged: docketEntry.lodged ?? null,
    mailingDate: docketEntry.mailingDate ?? null,
    noticeIssuedDate: docketEntry.noticeIssuedDate
      ? calculateDate({ dateString: docketEntry.noticeIssuedDate })
      : null,
    numberOfPages: docketEntry.numberOfPages ?? null,
    objections: docketEntry.objections ?? null,
    ordinalValue: docketEntry.ordinalValue ?? null,
    otherFilingParty: docketEntry.otherFilingParty ?? null,
    otherIteration: docketEntry.otherIteration ?? null,
    partyIrsPractitioner: docketEntry.partyIrsPractitioner ?? null,
    pending: docketEntry.pending ?? null,
    previousDocument: JSON.stringify(docketEntry.previousDocument) ?? null,
    privatePractitioners:
      JSON.stringify(docketEntry.privatePractitioners) ?? null,
    processingStatus: docketEntry.processingStatus,
    receivedAt: calculateDate({ dateString: docketEntry.receivedAt }),
    redactionAcknowledgement: docketEntry.redactionAcknowledgement ?? null,
    relationship: docketEntry.relationship ?? null,
    scenario: docketEntry.scenario ?? null,
    sealedTo: docketEntry.sealedTo,
    secondaryDocument: JSON.stringify(docketEntry.secondaryDocument) ?? null,
    servedAt: docketEntry.servedAt
      ? calculateDate({ dateString: docketEntry.servedAt })
      : null,
    servedParties: JSON.stringify(docketEntry.servedParties) ?? null,
    servedPartiesCode: docketEntry.servedPartiesCode ?? null,
    serviceDate: docketEntry.serviceDate
      ? calculateDate({ dateString: docketEntry.serviceDate })
      : null,
    serviceStamp: docketEntry.serviceStamp ?? null,
    signedAt: docketEntry.signedAt ?? null,
    signedByUserId: docketEntry.signedByUserId ?? null,
    signedJudgeName: docketEntry.signedJudgeName ?? null,
    signedJudgeUserId: docketEntry.signedJudgeUserId ?? null,
    stampData: JSON.stringify(docketEntry.stampData) ?? null,
    strickenAt: docketEntry.strickenAt
      ? calculateDate({ dateString: docketEntry.strickenAt })
      : null,
    strickenBy: docketEntry.strickenBy ?? null,
    strickenByUserId: docketEntry.strickenByUserId ?? null,
    supportingDocument: docketEntry.supportingDocument ?? null,
    taxYear: docketEntry.taxYear ?? null,
    trialLocation: docketEntry.trialLocation ?? null,
    userId: docketEntry.userId ?? null,
  };
}

export function fromKyselyDocketEntry<T extends object>(record: T) {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const dwDocketEntrySchema = DatabaseSchema.dwDocketEntry.table;

  const transformMap = {
    certificateOfServiceDate: (
      value: typeof dwDocketEntrySchema.certificateOfServiceDate,
      _: Partial<DocketEntry>,
    ) => value?.toISOString(),
    createdAt: (
      value: typeof dwDocketEntrySchema.createdAt,
      _: Partial<DocketEntry>,
    ) => value.toISOString(),
    date: (value: typeof dwDocketEntrySchema.date, _: Partial<DocketEntry>) =>
      value?.toISOString(),
    filingDate: (
      value: typeof dwDocketEntrySchema.filingDate,
      _: Partial<DocketEntry>,
    ) => value.toISOString(),
    noticeIssuedDate: (
      value: typeof dwDocketEntrySchema.noticeIssuedDate,
      _: Partial<DocketEntry>,
    ) => value?.toISOString(),
    receivedAt: (
      value: typeof dwDocketEntrySchema.receivedAt,
      _: Partial<DocketEntry>,
    ) => value.toISOString(),
    servedAt: (
      value: typeof dwDocketEntrySchema.servedAt,
      _: Partial<DocketEntry>,
    ) => value?.toISOString(),
    serviceDate: (
      value: typeof dwDocketEntrySchema.serviceDate,
      _: Partial<DocketEntry>,
    ) => value?.toISOString(),
    stampData: (
      value: typeof dwDocketEntrySchema.stampData,
      _: Partial<DocketEntry>,
    ) => value ?? {},
    strickenAt: (
      value: typeof dwDocketEntrySchema.strickenAt,
      _: Partial<DocketEntry>,
    ) => value?.toISOString(),
  } as const;

  return new DatabaseToAppCodeMapper({
    keyRenameMap: {},
    transformMap,
  }).transform(record);
}
