import { Selectable, Insertable, Updateable, ColumnType } from 'kysely';

const DEFAULT = {};

// TODO: This is just a stub to get things out of Open Search and into Postgres
export const docketEntryTableDefinition = {
  createdAt: DEFAULT as Date,
  docketEntryId: DEFAULT as string,
  docketNumber: DEFAULT as string,
  documentTitle: DEFAULT as string,
  documentType: DEFAULT as string,
  eventCode: DEFAULT as string,
  filingDate: DEFAULT as Date,
  isLegacyServed: DEFAULT as boolean,
  pending: DEFAULT as boolean,
  receivedAt: DEFAULT as Date,
  servedAt: DEFAULT as Date | null,
  isStricken: DEFAULT as boolean | null,
  judge: DEFAULT as string | null,
  signedJudgeName: DEFAULT as string | null,
  isSealed: DEFAULT as boolean | null,
  sealedTo: DEFAULT as string | undefined,
  numberOfPages: DEFAULT as number | undefined,

  action: DEFAULT as string | null,
  additionalInfo: DEFAULT as string | null,
  additionalInfo2: DEFAULT as string | null,
  addToCoversheet: DEFAULT as boolean | null,
  archived: DEFAULT as boolean | null,
  attachments: DEFAULT as boolean | null,
  caseType: DEFAULT as string | null,
  certificateOfService: DEFAULT as boolean | null,
  certificateOfServiceDate: DEFAULT as Date | null,
  date: DEFAULT as Date | null,
  docketNumbers: DEFAULT as string | null,
  documentContentsId: DEFAULT as string | null,
  documentIdBeforeSignature: DEFAULT as string | null,
  draftOrderState: DEFAULT as Record<string, any>,
  editState: DEFAULT as string | null,
  filedBy: DEFAULT as string | null,
  filedByRole: DEFAULT as string | null,
  filers: DEFAULT as string[],
  freeText: DEFAULT as string | null,
  hasOtherFilingParty: DEFAULT as boolean | null,
  hasSupportingDocuments: DEFAULT as boolean | null,
  index: DEFAULT as number | null,
  isAutoGenerated: DEFAULT as boolean | null,
  isDraft: DEFAULT as boolean | null,
  isFileAttached: DEFAULT as boolean | null,
  isLegacy: DEFAULT as boolean | null,
  isLegacySealed: DEFAULT as boolean | null,
  isOnDocketRecord: DEFAULT as boolean,
  isPaper: DEFAULT as boolean | null,
  isPendingService: DEFAULT as boolean | null,
  lodged: DEFAULT as boolean | null,
  mailingDate: DEFAULT as string | null,
  noticeIssuedDate: DEFAULT as string,
  objections: DEFAULT as string | null,
  ordinalValue: DEFAULT as string | null,
  otherFilingParty: DEFAULT as string | null,
  otherIteration: DEFAULT as string | null,
  partyIrsPractitioner: DEFAULT as boolean | null,
  // partyPrimary: DEFAULT as string, // Does not exist on docketEntry entity
  // partySecondary: DEFAULT as string, // Does not exist on docketEntry
  previousDocument: DEFAULT as ColumnType<
    {
      docketEntryId?: string;
      documentTitle: string;
      documentType: string;
    },
    string,
    string
  > | null,
  privatePractitioners: DEFAULT as ColumnType<
    {
      name: string;
      partyPrivatePractitioner?: boolean;
    }[],
    string,
    string
  > | null,
  processingStatus: DEFAULT as string,
  qcAt: DEFAULT as Date | null,
  qcByUserId: DEFAULT as string | null,
  redactionAcknowledgement: DEFAULT as boolean | null,
  relationship: DEFAULT as string | null,
  scenario: DEFAULT as string | null,
  secondaryDocument: DEFAULT as Record<string, any>,
  servedParties: DEFAULT as ColumnType<
    {
      name: string;
      role?: string;
      email?: string;
    }[],
    string,
    string
  > | null,
  servedPartiesCode: DEFAULT as string | null,
  serviceDate: DEFAULT as Date | null,
  serviceStamp: DEFAULT as string | null,
  signedAt: DEFAULT as Date | null,
  signedByUserId: DEFAULT as string | null,
  signedJudgeUserId: DEFAULT as string | null,
  stampData: DEFAULT as Record<string, any>,
  strickenAt: DEFAULT as Date | null,
  strickenBy: DEFAULT as string | null,
  strickenByUserId: DEFAULT as string | null,
  supportingDocument: DEFAULT as string | null,
  taxYear: DEFAULT as string | null,
  trialLocation: DEFAULT as string | null,
  userId: DEFAULT as string | null,
};

export type DocketEntryTable = typeof docketEntryTableDefinition;

export const DW_DOCKET_ENTRY_COLUMNS = Object.keys(
  docketEntryTableDefinition,
) as Array<keyof DocketEntryTable>;

export type DocketEntryKysely = Selectable<DocketEntryTable>;
export type NewDocketEntryKysely = Insertable<DocketEntryTable>;
export type UpdateDocketEntryKysely = Updateable<DocketEntryTable>;
