
pipeline {
  agent any

  // environment {
  //   SPAWN_WRAP_SHIM_ROOT = "/home/tomcat"
  //   npm_config_cache = "/home/tomcat"
  //   HOME = "/home/tomcat" // needed to run 'npm i' on docker without being root
  //   CYPRESS_CACHE_FOLDER = "/home/tomcat/cypress_cache" // needed to be able to run cypress without being root
  // }

  options { buildDiscarder(logRotator(daysToKeepStr: '3', artifactDaysToKeepStr: '3')) }

  stages {
    stage('Merge') {
      steps {
        script {
          if (env.branch_name != 'develop' && env.branch_name != 'staging' && env.branch_name != 'master' && env.target_sha1) {
            // todo: there is probably a better way to have Jenkins do this for us automatically
            sh 'git config user.name "EF-CMS Jenkins"'
            sh 'git config user.email "noop@example.com"'
            sh "git merge origin/${env.target_sha1}"
          }
        }
      }
    }
    stage('Audit') {
      steps {
        script {
          dir('isomorphic') {
            sh 'docker build -t isomorphic-audit -f Dockerfile.audit .'
            sh 'docker run --rm isomorphic-audit'
          }
        }
      }
    }
    stage('Lint') {
      steps {
        script {
          dir('isomorphic') {
            sh 'docker build -t isomorphic-lint -f Dockerfile.lint .'
            sh 'docker run --rm isomorphic-lint'
          }
        }
      }
    }
    stage('Test') {
      steps {
        script {
          dir('isomorphic') {
            def CONTAINER_NAME = "isomorphic-test-${BUILD_NUMBER}"
            sh 'docker build -t isomorphic-test -f Dockerfile.test .'
            sh "docker run --name ${CONTAINER_NAME} isomorphic-test"
            sh "docker cp ${CONTAINER_NAME}:/home/app/coverage coverage"
            sh "docker rm ${CONTAINER_NAME}"
          }
        }
      }
      post {
        success {
          dir('isomorphic') {
            publishHTML allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'coverage', reportFiles: 'index.html', reportName: 'Code Coverage Report', reportTitles: ''
          }
        }
      }
    }
    // TODO:
    // - create a new sonarqube token for the isomorphic job
    // - add that token to jenkins, uncomment this
    // - fix any code needed to be fixed in this commented out code
    // stage('SonarQube') {
    //   steps {
    //     script {
    //       withCredentials([string(credentialsId: 'API_SONAR_TOKEN', variable: 'SONAR_TOKEN')]) {
    //         dir('isomorphic') {
    //           sh 'docker build -t sonarqube -f Dockerfile.sonarqube .'
    //           sh "docker run -e branch_name=${branch_name} -e SONAR_ORG=${SONAR_ORG} -e SONAR_TOKEN=${SONAR_TOKEN} -v `pwd`/coverage:/home/app/coverage --rm sonarqube"
    //         }
    //       }
    //     }
    //   }
    // }
  }
  post {
    always {
      deleteDir()
    }
  }
}
