services:
  dawson-db:
    image: postgres:17.9-trixie
    platform: linux/amd64
    restart: always
    container_name: dawson-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - dawson-db:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dawson-db:
