export type DocketEntryMapping = {
  associatedJudge: string;
  caseCaption: string;
  createdAt: string;
  docketEntryId: string;
  docketNumber: string;
  docketNumberSuffix: string;
  docketNumberWithSuffix: string;
  documentContents: string;
  documentTitle: string;
  documentType: string;
  entityName: string;
  eventCode: string;
  filingDate: string;
  irsPractitioners: { userId: string }[];
  isFileAttached: boolean;
  isLegacyServed: boolean;
  isSealed: boolean;
  isStricken: boolean;
  judge: string;
  numberOfPages: number;
  pending: boolean;
  petitioners: { name: string }[];
  privatePractitioners: { userId: string }[];
  receivedAt: string;
  sealedDate: string;
  sealedTo: string;
  servedAt: string;
  servedPartiesCode: string;
  signedJudgeName: string;
  status: string;
};
