FROM cypress/base:16.17.1

WORKDIR /home/app

RUN echo "hello"

# TODO: find out what else this image doesn't need
RUN sh -c 'echo "deb [check-valid-until=no] http://ftp.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/stretch-backports.list'
RUN sed -i '/deb http:\/\/deb.debian.org\/debian stretch-backports main/d' /etc/apt/sources.list
RUN apt-get -o Acquire::Check-Valid-Until=false update

RUN apt-get install -y \
  graphicsmagick=1.4+really1.3.36+hg16481-2 \
  ghostscript=9.53.3~dfsg-7+deb11u2 

COPY . /home/app/efcms

CMD echo "🔥"
