# TODO: add package.json script to publish to dockerhub

FROM cypress/base:10.15.3

RUN sudo sh -c 'echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list'
RUN sudo sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list

RUN sudo apt-get -o Acquire::Check-Valid-Until=false update && \
  sudo apt-get install -y -t jessie-backports ca-certificates-java && \
  sudo apt-get -y install openjdk-8-jdk && update-alternatives --config java

RUN sudo wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1744-linux.zip
RUN sudo unzip sonar-scanner-cli-4.0.0.1744-linux.zip
RUN sudo rm sonar-scanner-cli-4.0.0.1744-linux.zip
RUN sudo mv sonar-scanner-4.0.0.1744-linux /tmp/sonar-scanner

RUN sudo apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
  libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
  libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
  libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
  ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget \
  git bash openssh-client python python-dev python-pip python-setuptools ca-certificates groff less \
  unzip wget jq shellcheck ghostscript libgs-dev clamav

RUN sudo freshclam

