FROM node:8

RUN apt-get update

RUN apt-get install -yq git bash shellcheck

WORKDIR /home/app

RUN apt-get install -y shellcheck

COPY shared/package.json /home/app/shared/package.json
COPY shared/package-lock.json /home/app/shared/package-lock.json
RUN cd /home/app/shared && npm ci

COPY . /home/app

CMD echo "please overwrite this command"