module.exports = {
  extends: [
    'stylelint-config-standard-scss',
    'stylelint-config-idiomatic-order',
    'stylelint-config-recommended',
  ],
  ignoreFiles: [
    '**/coverage/**',
    '**/dist/**',
    '**/build/**',
    '**/node_modules/**',
    '**/*.min.css',
  ],
  overrides: [
    {
      files: ['*.scss'],
      rules: {
        'media-query-no-invalid': null,
      },
    },
  ],
  rules: {
    'at-rule-no-unknown': null,
    'scss/at-rule-no-unknown': null,
    'function-no-unknown': [
      true,
      {
        ignoreFunctions: ['units', 'line-height', 'color', 'oklch'],
      },
    ],
    'declaration-property-value-no-unknown': null,
    'no-descending-specificity': null,
    'selector-class-pattern': null,
    'shorthand-property-no-redundant-values': null,
    'lightness-notation': null,
    'hue-degree-notation': null,
    'at-rule-empty-line-before': null,
    'rule-empty-line-before': null,
    'order/properties-order': null,
    'color-function-notation': null,
    'color-function-alias-notation': null,
    'alpha-value-notation': null,
    'length-zero-no-unit': null,
    'block-no-empty': null,
    'comment-empty-line-before': null,
    'declaration-block-single-line-max-declarations': null,
    'font-family-name-quotes': null,
    'font-family-no-missing-generic-family-keyword': null,
    'function-url-quotes': null,
    'media-feature-range-notation': null,
    'no-duplicate-selectors': null,
    'property-no-vendor-prefix': null,
    'selector-attribute-quotes': null,
    'selector-not-notation': null,
    'selector-pseudo-element-colon-notation': null,
    'value-keyword-case': null,
    'declaration-empty-line-before': null,
    'declaration-property-value-keyword-no-deprecated': null,
    'color-hex-length': null,
  },
};
