const {
  applicationContext,
} = require('../../test/createTestApplicationContext');
const {
  DOCUMENT_PROCESSING_STATUS_OPTIONS,
  SERVED_PARTIES_CODES,
  SYSTEM_GENERATED_DOCUMENT_TYPES,
} = require('../../entities/EntityConstants');
const {
  MOCK_TRIAL_INPERSON,
  MOCK_TRIAL_REMOTE,
} = require('../../../test/mockTrial');
const {
  setNoticeOfChangeToInPersonProceeding,
} = require('./setNoticeOfChangeToInPersonProceeding');
const { Case } = require('../../entities/cases/Case');
const { getFakeFile } = require('../../test/getFakeFile');
const { MOCK_CASE } = require('../../../test/mockCase');

describe('setNoticeOfChangeToInPersonProceeding', () => {
  const mockNumberOfPages = 123;
  const mockDocumentId = '98c6b1c8-1eed-44b6-932a-967af060597a';
  const mockTrialSessionId = '76a5b1c8-1eed-44b6-932a-967af060597a';
  const mockUserId = '85a5b1c8-1eed-44b6-932a-967af060597a';

  const mockInPersonCalendaredTrialSession = {
    ...MOCK_TRIAL_INPERSON,
    isCalendared: true,
    trialSessionId: mockTrialSessionId,
  };

  const mockRemoteTrialSession = {
    ...MOCK_TRIAL_REMOTE,
    trialSessionId: mockTrialSessionId,
  };

  const mockOpenCase = new Case(
    {
      ...MOCK_CASE,
      trialDate: '2019-03-01T21:42:29.073Z',
      trialSessionId: mockTrialSessionId,
    },
    { applicationContext },
  );

  beforeEach(() => {
    applicationContext.getUniqueId.mockReturnValue(mockDocumentId);

    applicationContext
      .getUseCaseHelpers()
      .generateNoticeOfChangeToInPersonProceeding.mockReturnValue(getFakeFile);

    applicationContext
      .getUseCaseHelpers()
      .countPagesInDocument.mockResolvedValue(mockNumberOfPages);
  });

  it('should save the generated NOIP to persistence', async () => {
    await setNoticeOfChangeToInPersonProceeding(applicationContext, {
      caseEntity: mockOpenCase,
      currentTrialSession: mockRemoteTrialSession,
      newPdfDoc: getFakeFile,
      newTrialSessionEntity: mockInPersonCalendaredTrialSession,
      userId: mockUserId,
    });

    expect(
      applicationContext.getPersistenceGateway().saveDocumentFromLambda.mock
        .calls[0][0],
    ).toMatchObject({
      document: getFakeFile,
      key: mockDocumentId,
    });
  });

  it('should create and serve the NOIP docket entry on the case', async () => {
    await setNoticeOfChangeToInPersonProceeding(applicationContext, {
      caseEntity: mockOpenCase,
      currentTrialSession: mockRemoteTrialSession,
      newPdfDoc: getFakeFile,
      newTrialSessionEntity: mockInPersonCalendaredTrialSession,
      userId: mockUserId,
    });

    const noipDocketEntry =
      applicationContext.getUseCaseHelpers().serveGeneratedNoticesOnCase.mock
        .calls[0][0].noticeDocketEntryEntity;

    expect(noipDocketEntry).toMatchObject({
      docketEntryId: mockDocumentId,
      docketNumber: MOCK_CASE.docketNumber,
      documentTitle:
        SYSTEM_GENERATED_DOCUMENT_TYPES.noticeOfChangeToInPersonProceeding
          .documentTitle,
      documentType:
        SYSTEM_GENERATED_DOCUMENT_TYPES.noticeOfChangeToInPersonProceeding
          .documentType,
      eventCode:
        SYSTEM_GENERATED_DOCUMENT_TYPES.noticeOfChangeToInPersonProceeding
          .eventCode,
      isAutoGenerated: true,
      isFileAttached: true,
      isOnDocketRecord: true,
      numberOfPages: mockNumberOfPages,
      processingStatus: DOCUMENT_PROCESSING_STATUS_OPTIONS.COMPLETE,
      servedParties: [
        {
          email: 'petitioner@example.com',
          name: 'Test Petitioner',
        },
      ],
      servedPartiesCode: SERVED_PARTIES_CODES.BOTH,
      signedAt: expect.anything(),
    });
  });
});
