/*
 * dev-ef-cms
 * Documents API for U.S. Tax Court EF-CMS
 *
 * OpenAPI spec version: 2019-03-06T15:30:48Z
 * Contact: webmaster@ustaxcourt.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AuthLoginBody model module.
 * @module model/AuthLoginBody
 * @version 2019-03-06T15:30:48Z
 */
export class AuthLoginBody {
  /**
   * Constructs a new <code>AuthLoginBody</code>.
   * @alias module:model/AuthLoginBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AuthLoginBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthLoginBody} obj Optional instance to populate.
   * @return {module:model/AuthLoginBody} The populated <code>AuthLoginBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AuthLoginBody();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} code
 */
AuthLoginBody.prototype.code = undefined;

