/*
 * dev-ef-cms
 * Documents API for U.S. Tax Court EF-CMS
 *
 * OpenAPI spec version: 2019-03-06T15:30:48Z
 * Contact: webmaster@ustaxcourt.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata model module.
 * @module model/CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata
 * @version 2019-03-06T15:30:48Z
 */
export class CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata {
  /**
   * Constructs a new <code>CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata</code>.
   * @alias module:model/CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata} obj Optional instance to populate.
   * @return {module:model/CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata} The populated <code>CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata();
      if (data.hasOwnProperty('docketNumber'))
        obj.docketNumber = ApiClient.convertToType(data['docketNumber'], 'String');
      if (data.hasOwnProperty('documentTitle'))
        obj.documentTitle = ApiClient.convertToType(data['documentTitle'], 'String');
      if (data.hasOwnProperty('documentType'))
        obj.documentType = ApiClient.convertToType(data['documentType'], 'String');
      if (data.hasOwnProperty('draftOrderState'))
        obj.draftOrderState = ApiClient.convertToType(data['draftOrderState'], Object);
      if (data.hasOwnProperty('eventCode'))
        obj.eventCode = ApiClient.convertToType(data['eventCode'], 'String');
      if (data.hasOwnProperty('richText'))
        obj.richText = ApiClient.convertToType(data['richText'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} docketNumber
 */
CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata.prototype.docketNumber = undefined;

/**
 * @member {String} documentTitle
 */
CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata.prototype.documentTitle = undefined;

/**
 * @member {String} documentType
 */
CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata.prototype.documentType = undefined;

/**
 * @member {Object} draftOrderState
 */
CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata.prototype.draftOrderState = undefined;

/**
 * @member {String} eventCode
 */
CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata.prototype.eventCode = undefined;

/**
 * @member {String} richText
 */
CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata.prototype.richText = undefined;

