/*
 * dev-ef-cms
 * Documents API for U.S. Tax Court EF-CMS
 *
 * OpenAPI spec version: 2019-03-06T15:30:48Z
 * Contact: webmaster@ustaxcourt.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DocumentContents model module.
 * @module model/DocumentContents
 * @version 2019-03-06T15:30:48Z
 */
export class DocumentContents {
  /**
   * Constructs a new <code>DocumentContents</code>.
   * a document contents response with both plain and rich-text
   * @alias module:model/DocumentContents
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DocumentContents</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentContents} obj Optional instance to populate.
   * @return {module:model/DocumentContents} The populated <code>DocumentContents</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DocumentContents();
      if (data.hasOwnProperty('documentContents'))
        obj.documentContents = ApiClient.convertToType(data['documentContents'], 'String');
      if (data.hasOwnProperty('richText'))
        obj.richText = ApiClient.convertToType(data['richText'], 'String');
    }
    return obj;
  }
}

/**
 * plain text with line breaks for a an associated docket-entry's document contents
 * @member {String} documentContents
 */
DocumentContents.prototype.documentContents = undefined;

/**
 * rich text with line breaks for a an associated docket-entry's document contents
 * @member {String} richText
 */
DocumentContents.prototype.richText = undefined;

