/*
 * dev-ef-cms
 * Documents API for U.S. Tax Court EF-CMS
 *
 * OpenAPI spec version: 2019-03-06T15:30:48Z
 * Contact: webmaster@ustaxcourt.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The HealthDynamo model module.
 * @module model/HealthDynamo
 * @version 2019-03-06T15:30:48Z
 */
export class HealthDynamo {
  /**
   * Constructs a new <code>HealthDynamo</code>.
   * @alias module:model/HealthDynamo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HealthDynamo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HealthDynamo} obj Optional instance to populate.
   * @return {module:model/HealthDynamo} The populated <code>HealthDynamo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HealthDynamo();
      if (data.hasOwnProperty('efcms'))
        obj.efcms = ApiClient.convertToType(data['efcms'], 'Boolean');
      if (data.hasOwnProperty('efcmsDeploy'))
        obj.efcmsDeploy = ApiClient.convertToType(data['efcmsDeploy'], 'Boolean');
    }
    return obj;
  }
}

/**
 * the status of main dynamo table
 * @member {Boolean} efcms
 */
HealthDynamo.prototype.efcms = undefined;

/**
 * the status of deploy dynamo table
 * @member {Boolean} efcmsDeploy
 */
HealthDynamo.prototype.efcmsDeploy = undefined;

