/*
 * dev-ef-cms
 * Documents API for U.S. Tax Court EF-CMS
 *
 * OpenAPI spec version: 2019-03-06T15:30:48Z
 * Contact: webmaster@ustaxcourt.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ParentMessageIdForwardBody1 model module.
 * @module model/ParentMessageIdForwardBody1
 * @version 2019-03-06T15:30:48Z
 */
export class ParentMessageIdForwardBody1 {
  /**
   * Constructs a new <code>ParentMessageIdForwardBody1</code>.
   * @alias module:model/ParentMessageIdForwardBody1
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ParentMessageIdForwardBody1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ParentMessageIdForwardBody1} obj Optional instance to populate.
   * @return {module:model/ParentMessageIdForwardBody1} The populated <code>ParentMessageIdForwardBody1</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ParentMessageIdForwardBody1();
      if (data.hasOwnProperty('attachments'))
        obj.attachments = ApiClient.convertToType(data['attachments'], Array);
      if (data.hasOwnProperty('docketNumber'))
        obj.docketNumber = ApiClient.convertToType(data['docketNumber'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('subject'))
        obj.subject = ApiClient.convertToType(data['subject'], 'String');
      if (data.hasOwnProperty('toSection'))
        obj.toSection = ApiClient.convertToType(data['toSection'], 'String');
      if (data.hasOwnProperty('toUserId'))
        obj.toUserId = ApiClient.convertToType(data['toUserId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array} attachments
 */
ParentMessageIdForwardBody1.prototype.attachments = undefined;

/**
 * @member {String} docketNumber
 */
ParentMessageIdForwardBody1.prototype.docketNumber = undefined;

/**
 * @member {String} message
 */
ParentMessageIdForwardBody1.prototype.message = undefined;

/**
 * @member {String} subject
 */
ParentMessageIdForwardBody1.prototype.subject = undefined;

/**
 * @member {String} toSection
 */
ParentMessageIdForwardBody1.prototype.toSection = undefined;

/**
 * @member {String} toUserId
 */
ParentMessageIdForwardBody1.prototype.toUserId = undefined;

