/*
 * dev-ef-cms
 * Documents API for U.S. Tax Court EF-CMS
 *
 * OpenAPI spec version: 2019-03-06T15:30:48Z
 * Contact: webmaster@ustaxcourt.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TrialSessionIdPrintableworkingcopyBody model module.
 * @module model/TrialSessionIdPrintableworkingcopyBody
 * @version 2019-03-06T15:30:48Z
 */
export class TrialSessionIdPrintableworkingcopyBody {
  /**
   * Constructs a new <code>TrialSessionIdPrintableworkingcopyBody</code>.
   * @alias module:model/TrialSessionIdPrintableworkingcopyBody
   * @class
   * @param showCaseNotes {Boolean} 
   * @param filters {Object} 
   * @param formattedCases {Array} 
   * @param formattedTrialSession {Object} 
   * @param sort {String} 
   * @param userHeading {String} 
   */
  constructor(showCaseNotes, filters, formattedCases, formattedTrialSession, sort, userHeading) {
    this.showCaseNotes = showCaseNotes;
    this.filters = filters;
    this.formattedCases = formattedCases;
    this.formattedTrialSession = formattedTrialSession;
    this.sort = sort;
    this.userHeading = userHeading;
  }

  /**
   * Constructs a <code>TrialSessionIdPrintableworkingcopyBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrialSessionIdPrintableworkingcopyBody} obj Optional instance to populate.
   * @return {module:model/TrialSessionIdPrintableworkingcopyBody} The populated <code>TrialSessionIdPrintableworkingcopyBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TrialSessionIdPrintableworkingcopyBody();
      if (data.hasOwnProperty('showCaseNotes'))
        obj.showCaseNotes = ApiClient.convertToType(data['showCaseNotes'], 'Boolean');
      if (data.hasOwnProperty('filters'))
        obj.filters = ApiClient.convertToType(data['filters'], Object);
      if (data.hasOwnProperty('formattedCases'))
        obj.formattedCases = ApiClient.convertToType(data['formattedCases'], Array);
      if (data.hasOwnProperty('formattedTrialSession'))
        obj.formattedTrialSession = ApiClient.convertToType(data['formattedTrialSession'], Object);
      if (data.hasOwnProperty('sessionNotes'))
        obj.sessionNotes = ApiClient.convertToType(data['sessionNotes'], 'String');
      if (data.hasOwnProperty('sort'))
        obj.sort = ApiClient.convertToType(data['sort'], 'String');
      if (data.hasOwnProperty('userHeading'))
        obj.userHeading = ApiClient.convertToType(data['userHeading'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Boolean} showCaseNotes
 */
TrialSessionIdPrintableworkingcopyBody.prototype.showCaseNotes = undefined;

/**
 * @member {Object} filters
 */
TrialSessionIdPrintableworkingcopyBody.prototype.filters = undefined;

/**
 * @member {Array} formattedCases
 */
TrialSessionIdPrintableworkingcopyBody.prototype.formattedCases = undefined;

/**
 * @member {Object} formattedTrialSession
 */
TrialSessionIdPrintableworkingcopyBody.prototype.formattedTrialSession = undefined;

/**
 * @member {String} sessionNotes
 */
TrialSessionIdPrintableworkingcopyBody.prototype.sessionNotes = undefined;

/**
 * @member {String} sort
 */
TrialSessionIdPrintableworkingcopyBody.prototype.sort = undefined;

/**
 * @member {String} userHeading
 */
TrialSessionIdPrintableworkingcopyBody.prototype.userHeading = undefined;

