/*
 * dev-ef-cms
 * Documents API for U.S. Tax Court EF-CMS
 *
 * OpenAPI spec version: 2019-03-06T15:30:48Z
 * Contact: webmaster@ustaxcourt.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The WorkItemMessages model module.
 * @module model/WorkItemMessages
 * @version 2019-03-06T15:30:48Z
 */
export class WorkItemMessages {
  /**
   * Constructs a new <code>WorkItemMessages</code>.
   * @alias module:model/WorkItemMessages
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>WorkItemMessages</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WorkItemMessages} obj Optional instance to populate.
   * @return {module:model/WorkItemMessages} The populated <code>WorkItemMessages</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WorkItemMessages();
      if (data.hasOwnProperty('messageType'))
        obj.messageType = ApiClient.convertToType(data['messageType'], 'String');
      if (data.hasOwnProperty('messageId'))
        obj.messageId = ApiClient.convertToType(data['messageId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} messageType
 */
WorkItemMessages.prototype.messageType = undefined;

/**
 * @member {String} messageId
 */
WorkItemMessages.prototype.messageId = undefined;

