/*
 * dev-ef-cms
 * Documents API for U.S. Tax Court EF-CMS
 *
 * OpenAPI spec version: 2019-03-06T15:30:48Z
 * Contact: webmaster@ustaxcourt.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The WorkItemDocument model module.
 * @module model/WorkItemDocument
 * @version 2019-03-06T15:30:48Z
 */
export class WorkItemDocument {
  /**
   * Constructs a new <code>WorkItemDocument</code>.
   * @alias module:model/WorkItemDocument
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>WorkItemDocument</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WorkItemDocument} obj Optional instance to populate.
   * @return {module:model/WorkItemDocument} The populated <code>WorkItemDocument</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WorkItemDocument();
      if (data.hasOwnProperty('documentType'))
        obj.documentType = ApiClient.convertToType(data['documentType'], 'String');
      if (data.hasOwnProperty('docketEntryId'))
        obj.docketEntryId = ApiClient.convertToType(data['docketEntryId'], 'String');
      if (data.hasOwnProperty('createAt'))
        obj.createAt = ApiClient.convertToType(data['createAt'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} documentType
 */
WorkItemDocument.prototype.documentType = undefined;

/**
 * @member {String} docketEntryId
 */
WorkItemDocument.prototype.docketEntryId = undefined;

/**
 * @member {String} createAt
 */
WorkItemDocument.prototype.createAt = undefined;

