import { FILING_FEE_DEADLINE_DESCRIPTION } from '../../../shared/src/business/entities/EntityConstants';
import { caseDetailHelper as caseDetailHelperComputed } from '../../src/presenter/computeds/caseDetailHelper';
import { runCompute } from 'cerebral/test';
import { withAppContextDecorator } from '../../src/withAppContext';

const caseDetailHelper = withAppContextDecorator(caseDetailHelperComputed);

export const docketClerkViewsAutoGeneratedCaseDeadline = cerebralTest => {
  return it('Docket clerk views autogenerated case deadline', async () => {
    await cerebralTest.runSequence('gotoCaseDetailSequence', {
      docketNumber: cerebralTest.docketNumber,
    });

    const helper = runCompute(caseDetailHelper, {
      state: cerebralTest.getState(),
    });

    expect(helper.caseDeadlines[0].deadlineDate).toEqual(
      '2050-02-02T05:00:00.000Z',
    );
    expect(helper.caseDeadlines[0].description).toEqual(
      FILING_FEE_DEADLINE_DESCRIPTION,
    );
  });
};
