name: DAWSON Container Images
description: Build the DAWSON base and local container images in dependency order.

runs:
  using: composite
  steps:
    - name: Build DAWSON base image
      shell: bash
      run: docker build --platform=linux/amd64 -t ef-cms-us-east-1 -f Dockerfile .

    - name: Build DAWSON local image
      shell: bash
      run: docker build --platform=linux/amd64 -t efcms-local -f Dockerfile-local .
