#!/usr/bin/env -S npx ts-node --transpile-only

import {
  AUDIT_COLUMNS,
  type RangeReader,
  auditDocument,
  formatDuplicates,
  mapWithConcurrency,
  summarize,
  toCsvLine,
} from './pdf-audit.helpers';
import { Agent } from 'https';
import { NodeHttpHandler } from '@smithy/node-http-handler';
import { PDFDocument } from 'pdf-lib';
import { S3 } from '@aws-sdk/client-s3';
import {
  type ScriptConfig,
  parseArgsAndEnvVars,
} from '../helpers/parseArgsAndEnvVars';
import {
  calculateDate,
  getIsoFromJsDate,
} from '@shared/business/utilities/DateHandler';
import { createApplicationContext } from '@web-api/applicationContext';
import { findDuplicateObjectNumbers } from './pdf-doctor.helpers';
import { getDbReader } from '@web-api/persistence/postgres/database';
import { writeFileSync } from 'fs';

const scriptConfig: ScriptConfig = {
  description:
    "pdf-audit - surveys stored documents for the duplicated-object-number defect, reading only each document's trailing bytes. Read-only: it never writes to S3 or the database.",
  environment: {
    env: 'ENV',
  },
  parameters: {
    concurrency: {
      default: '100',
      description:
        'documents surveyed in parallel; also the size of the connection pool, so raising it genuinely raises throughput',
      type: 'string',
    },
    deep: {
      description:
        'download the whole file for flagged documents only, to settle every RESIDUE candidate definitively and name the /Type of each duplicated object',
      type: 'boolean',
    },
    endDate: {
      description: 'survey documents created on or before this date, ISO 8601',
      position: 1,
      required: true,
      type: 'string',
    },
    limit: {
      description:
        'survey at most this many documents - the OLDEST in the range, or the newest with --newest. This truncates rather than samples, so a small limit over a wide range only covers its first few days',
      type: 'string',
    },
    newest: {
      description:
        'take the most recently created documents rather than the oldest; only meaningful with --limit',
      type: 'boolean',
    },
    output: {
      default: 'pdf-audit.csv',
      description: 'path to write the CSV report to',
      type: 'string',
    },
    startDate: {
      description: 'survey documents created on or after this date, ISO 8601',
      position: 0,
      required: true,
      type: 'string',
    },
  },
  requireActiveAwsSession: true,
};

const { concurrency, deep, endDate, limit, newest, output, startDate } =
  parseArgsAndEnvVars(scriptConfig) as {
    concurrency: string;
    deep?: boolean;
    endDate: string;
    limit?: string;
    newest?: boolean;
    output: string;
    startDate: string;
  };

type StoredDocument = {
  createdAt: Date;
  documentStorageId: string;
  eventCode: string;
  isAutoGenerated: boolean | null;
};

/**
 * Every docket entry with a file attached in the window. Enumerating from the
 * database rather than by listing the bucket keeps the survey to documents the
 * application actually references, and gives each one a creation date that a
 * bucket listing cannot: S3's LastModified changes on any later copy.
 */
const listDocuments = async (): Promise<StoredDocument[]> =>
  getDbReader(reader => {
    const query = reader
      .selectFrom('dwDocketEntry as d')
      .select([
        'd.createdAt',
        'd.documentStorageId',
        'd.eventCode',
        'd.isAutoGenerated',
      ])
      .where('d.createdAt', '>=', calculateDate({ dateString: startDate }))
      .where('d.createdAt', '<=', calculateDate({ dateString: endDate }))
      .where('d.isFileAttached', 'is', true)
      // With --limit this decides *which* documents are surveyed, not just
      // their order: the limit truncates the range rather than sampling it.
      .orderBy('d.createdAt', limit && newest ? 'desc' : 'asc');

    return (limit ? query.limit(Number(limit)) : query).execute();
  });

// eslint-disable-next-line @typescript-eslint/no-floating-promises
(async () => {
  const applicationContext = createApplicationContext({});
  const { documentsBucketName, region, s3Endpoint } =
    applicationContext.environment;
  const parallelism = Number(concurrency);

  /**
   * A client of this survey's own rather than the shared `getStorageClient`,
   * whose pool is fixed at 75 sockets. That ceiling silently caps how much of
   * `--concurrency` actually runs: past it the extra workers just queue for a
   * connection. Sizing the pool to the requested concurrency is what makes the
   * flag mean something.
   *
   * Adaptive retries let the SDK back off on its own if S3 starts throttling,
   * so a concurrency set too high degrades rather than fails.
   */
  const storage = new S3({
    endpoint: s3Endpoint,
    forcePathStyle: true,
    maxAttempts: 5,
    region,
    requestHandler: new NodeHttpHandler({
      connectionTimeout: 3000,
      httpsAgent: new Agent({ keepAlive: true, maxSockets: parallelism }),
      requestTimeout: 30000,
    }),
    retryMode: 'adaptive',
  });

  const readRange =
    (key: string): RangeReader =>
    async range => {
      const response = await storage.getObject({
        Bucket: documentsBucketName,
        Key: key,
        Range: range,
      });

      return {
        bytes: await response.Body!.transformToByteArray(),
        contentRange: response.ContentRange,
      };
    };

  /**
   * Phase two, run only on documents the survey has already flagged. Reads the
   * whole document and enumerates its objects directly, so unlike the
   * byte-level screen it does not depend on offsets being trustworthy — which
   * is what lets it settle a candidate either way.
   */
  const surveyDuplicates = async (
    key: string,
  ): Promise<{ count: number; types: string }> => {
    const response = await storage.getObject({
      Bucket: documentsBucketName,
      Key: key,
    });
    const pdfDoc = await PDFDocument.load(
      await response.Body!.transformToByteArray(),
      {
        ignoreEncryption: true,
        throwOnInvalidObject: false,
        updateMetadata: false,
      },
    );
    const { duplicates } = findDuplicateObjectNumbers(pdfDoc);

    return { count: duplicates.length, types: formatDuplicates(duplicates) };
  };

  console.log(`surveying documents created ${startDate} to ${endDate} ...`);
  if (limit) {
    console.log(
      `  limited to the ${newest ? 'newest' : 'oldest'} ${limit}, so this covers only part of that range`,
    );
  }
  const documents = await listDocuments();
  console.log(`  ${documents.length} document(s) with a file attached`);
  if (!documents.length) {
    return;
  }
  console.log(`  ${parallelism} in parallel`);

  let completed = 0;
  let bytesRead = 0;
  let requests = 0;
  const startedAt = performance.now();
  const elapsedSeconds = (): number => (performance.now() - startedAt) / 1000;

  const rows = await mapWithConcurrency(
    documents,
    parallelism,
    async document => {
      const createdAt = getIsoFromJsDate(document.createdAt) ?? '';
      let status: string;
      let reason: string;
      let size: number | null = null;
      let entryCount: number | null = null;
      let displacedObjectNumber: number | null = null;
      let residue = '';
      let duplicateTypes = '';

      try {
        const outcome = await auditDocument(
          readRange(document.documentStorageId),
        );
        ({ displacedObjectNumber, entryCount, reason, size, status } = outcome);
        residue = outcome.residue.map(entry => entry.objectNumber).join(' ');
        bytesRead += outcome.bytesRead;
        requests += outcome.requests;

        // Candidates are the point of --deep: a full read settles what the
        // trailing bytes could not. Confirmed hits are surveyed too, to name
        // the object that actually collided and its /Type.
        if (deep && (status === 'DUPLICATED' || status === 'RESIDUE')) {
          // Kept out of the outer catch on purpose. A document damaged badly
          // enough to defeat pdf-lib is the strongest evidence there is, so a
          // failure here must not be allowed to overwrite the verdict already
          // reached from its cross-reference section.
          try {
            const survey = await surveyDuplicates(document.documentStorageId);
            duplicateTypes = survey.types;

            if (status === 'RESIDUE') {
              status = survey.count ? 'DUPLICATED' : 'VALID';
              reason = survey.count
                ? `a full read of the document found ${survey.count} duplicated object number(s)`
                : 'a full read of the document found no duplicated object number';
            }
          } catch (error) {
            duplicateTypes = `unreadable: ${(error as Error).message.split('\n')[0]}`;
          }
        }
      } catch (error) {
        status = 'UNREADABLE';
        reason = (error as Error).message.split('\n')[0];
      }

      completed += 1;
      if (completed % 500 === 0) {
        const rate = completed / elapsedSeconds();
        const remaining = (documents.length - completed) / rate;
        console.log(
          `  ${completed}/${documents.length}  ${rate.toFixed(0)}/s  ~${(remaining / 60).toFixed(0)}m left`,
        );
      }

      return {
        createdAt,
        documentStorageId: document.documentStorageId,
        duplicateTypes,
        displacedObjectNumber,
        entryCount,
        eventCode: document.eventCode,
        isAutoGenerated: document.isAutoGenerated,
        reason,
        residue,
        size,
        status,
      };
    },
  );

  writeFileSync(
    output,
    [
      toCsvLine([...AUDIT_COLUMNS]),
      ...rows.map(row =>
        toCsvLine(AUDIT_COLUMNS.map(column => row[column as keyof typeof row])),
      ),
    ].join('\n') + '\n',
  );

  const summary = summarize(rows);

  console.log('');
  console.log('--- verdicts ---');
  for (const { count, status } of summary.byStatus) {
    const share = ((count / rows.length) * 100).toFixed(2);
    console.log(
      `  ${status.padEnd(15)} ${String(count).padStart(8)}  ${share}%`,
    );
  }

  const confirmed = summary.byStatus.find(
    entry => entry.status === 'DUPLICATED',
  );
  const candidates = summary.byStatus.find(entry => entry.status === 'RESIDUE');

  console.log('');
  console.log(
    `  ${confirmed?.count ?? 0} confirmed, ${candidates?.count ?? 0} unproven candidate(s);`,
  );
  console.log(
    `  the number actually affected is between ${confirmed?.count ?? 0} and ${(confirmed?.count ?? 0) + (candidates?.count ?? 0)}.`,
  );

  console.log('');
  console.log('--- confirmed by month ---');
  for (const { affected, month, total } of summary.byMonth) {
    const share = total ? ((affected / total) * 100).toFixed(2) : '0.00';
    console.log(
      `  ${month}  ${String(affected).padStart(6)} / ${String(total).padStart(7)}  ${share}%`,
    );
  }

  const elapsed = elapsedSeconds();

  console.log('');
  console.log(
    `  ${requests} range request(s), ${(bytesRead / 1024 / 1024).toFixed(1)} MB read`,
  );
  // Reported so the concurrency can be tuned against a measurement rather than
  // a guess: re-run a --limit sample at a higher value and compare.
  console.log(
    `  ${(elapsed / 60).toFixed(1)} min at ${(rows.length / elapsed).toFixed(0)} document(s)/s`,
  );
  console.log(`  report written to ${output}`);
})();
