import { AuthUser } from '@shared/business/entities/authUser/AuthUser';
import { Case } from '@shared/business/entities/cases/Case';
import {
  DocketEntry,
  getServedPartiesCode,
} from '@shared/business/entities/DocketEntry';
import {
  DOCUMENT_PROCESSING_STATUS_OPTIONS,
  PARTIES_CODES,
} from '@shared/business/entities/EntityConstants';
import { aggregatePartiesForService } from '@shared/business/utilities/aggregatePartiesForService';
import { createISODateString } from '@shared/business/utilities/DateHandler';
import { ServerApplicationContext } from '@web-api/applicationContext';
import { PDFDocument } from 'pdf-lib';
import { countPagesInDocument } from '../countPagesInDocument';

type CreateAndServeNoticeDocketEntryParams = {
  additionalDocketEntryInfo?: any;
  caseEntity: Case;
  documentInfo: {
    documentType: string;
    documentTitle: string;
    eventCode: string;
  };
  newPdfDoc: PDFDocument;
  noticePdf: Uint8Array;
  onlyProSePetitioners?: boolean;
};

export const createAndServeNoticeDocketEntry = async (
  applicationContext: ServerApplicationContext,
  {
    additionalDocketEntryInfo = {},
    caseEntity,
    documentInfo,
    newPdfDoc,
    noticePdf,
    onlyProSePetitioners,
  }: CreateAndServeNoticeDocketEntryParams,
  authorizedUser: AuthUser,
): Promise<() => Promise<void>> => {
  const documentStorageId = applicationContext.getUniqueId();

  await applicationContext.getPersistenceGateway().saveDocumentFromLambda({
    document: noticePdf,
    key: documentStorageId,
  });

  const servedParties = aggregatePartiesForService(caseEntity, {
    onlyProSePetitioners,
  });

  const numberOfPages = await countPagesInDocument({
    applicationContext,
    documentStorageId,
  });

  const noticeDocketEntry = new DocketEntry(
    {
      docketEntryId: documentStorageId,
      documentStorageId,
      documentTitle: documentInfo.documentTitle,
      documentType: documentInfo.documentType,
      eventCode: documentInfo.eventCode,
      isAutoGenerated: true,
      isFileAttached: true,
      isOnDocketRecord: true,
      numberOfPages,
      originallyFiledDocketNumber: caseEntity.docketNumber,
      processingStatus: DOCUMENT_PROCESSING_STATUS_OPTIONS.COMPLETE,
      servedAt: createISODateString(),
      servedParties: servedParties.all,
      servedPartiesCode: onlyProSePetitioners
        ? PARTIES_CODES.PETITIONER
        : getServedPartiesCode(servedParties.all),
      ...additionalDocketEntryInfo,
    },
    { authorizedUser },
  );

  noticeDocketEntry.setFiledBy(authorizedUser);

  caseEntity.addDocketEntry(noticeDocketEntry);

  return applicationContext.getUseCaseHelpers().serveGeneratedNoticesOnCase({
    applicationContext,
    caseEntity,
    newPdfDoc,
    noticeDocketEntryEntity: noticeDocketEntry,
    noticeDocumentPdfData: noticePdf,
    servedParties,
    skipEmailToIrs: onlyProSePetitioners,
  });
};
