version: '3.9'
services:
  message-service:
    image: postgres
    restart: always
    container_name: message-service
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
