service: ef-cms-users
plugins:
  # - serverless-plugin-split-stacks
  - serverless-domain-manager
  - serverless-plugin-bind-deployment-id
  # - serverless-plugin-aws-alerts
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-tracing
  - serverless-latest-layer-version
  - serverless-jetpack
  # - serverless-plugin-warmup

custom:
  #warmup:
  #enabled: true

  jetpack:
    mode: yarn

  prune:
    automatic: true
    number: 3

  serverless-offline:
    host: 0.0.0.0
    port: 3003

  alerts:
    stages:
      - dev
      - stg
      - prod
    dashboards: true
    alarms:
      - functionThrottles
      - functionErrors
      - functionInvocations
      - functionDuration
      - errorExceptions
    definitions:
      errorExceptions:
        description: 'Internal Error Exception Alarm'
        namespace: 'AWS/Lambda'
        metric: Errors
        threshold: 1
        statistic: Sum
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanThreshold
        pattern: 'ERROR'
    topics:
      alarm:
        topic: ${self:provider.stage}-cloudwatch-alerts
        notifications:
          - protocol: email
            endpoint: jsutton@flexion.us

  customDomain:
    domainName: efcms-${self:provider.stage}.${opt:domain}
    basePath: 'users'
    endpointType: 'regional'
    certificateName: efcms-${self:provider.stage}.${opt:domain}
    certificateRegion: ${opt:region}
    stage: ${self:provider.stage}
    createRoute53Record: false
    enabled: true
  splitStacks:
    perFunction: true
    perType: true
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  vars: ${file(./config/${self:custom.stage}.yml)}

provider:
  name: aws
  tracing: true
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  runtime: nodejs12.x
  memorySize: 768
  timeout: 30
  logRetentionInDays: 7
  role: arn:aws:iam::${opt:accountId}:role/lambda_role_${opt:stage}
  dir: ${opt:run_dir, 'src'}
  s3Endpoint: s3.us-east-1.amazonaws.com
  dynamodbEndpoint: dynamodb.${opt:region}.amazonaws.com
  masterRegion: us-east-1
  userPoolId: us-east-1_7uRkF0Axn
  masterDynamodbEndpoint: dynamodb.us-east-1.amazonaws.com
  deploymentBucket:
    name: ${env:SLS_DEPLOYMENT_BUCKET}
    serverSideEncryption: AES256
  apiGateway:
    binaryMediaTypes:
      - 'application/pdf'
  clamavDefDir: /opt/var/lib/clamav

  environment:
    S3_ENDPOINT: ${self:custom.vars.s3Endpoint, self:provider.s3Endpoint}
    DOCUMENTS_BUCKET_NAME: ${opt:domain}-documents-${opt:stage}-us-east-1
    TEMP_DOCUMENTS_BUCKET_NAME: ${opt:domain}-temp-documents-${opt:stage}-us-east-1
    DYNAMODB_ENDPOINT: ${self:custom.vars.dynamodbEndpoint, self:provider.dynamodbEndpoint}
    MASTER_DYNAMODB_ENDPOINT: ${self:custom.vars.masterDynamodbEndpoint, self:provider.masterDynamodbEndpoint}
    MASTER_REGION: ${self:provider.masterRegion}
    STAGE: ${self:custom.stage}
    USER_POOL_ID: ${opt:userPoolId, self:provider.userPoolId}
    NODE_ENV: ${self:custom.vars.nodeEnv}
    CLAMAV_DEF_DIR: ${self:custom.vars.clamavDefDir, self:provider.clamavDefDir}

package:
  exclude:
    - ./**
  include:
    - web-api/${self:provider.dir}/usersHandlers.js
  excludeDevDependencies: true

resources:
  Resources:
    #####
    # This Authorizer is used for validating the JWT token before invoking the lambda
    #####
    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: CognitoUserPool
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        ProviderARNs:
          - arn:aws:cognito-idp:${opt:region}:${opt:accountId}:userpool/${self:provider.environment.USER_POOL_ID}

    #####
    # Begin Stage for API Gateway Logging
    #####
    ApiGatewayStage:
      Type: AWS::ApiGateway::Stage
      Properties:
        DeploymentId:
          Ref: __deployment__
        RestApiId:
          Ref: ApiGatewayRestApi
        StageName: ${opt:stage}
        MethodSettings:
          - DataTraceEnabled: true
            HttpMethod: '*'
            LoggingLevel: INFO
            ResourcePath: '/*'
            MetricsEnabled: true

functions:
  getUser:
    handler: web-api/${self:provider.dir}/usersHandlers.getUserLambda
    events:
      - http:
          path: /
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  getInternalUsers:
    handler: web-api/${self:provider.dir}/usersHandlers.getInternalUsersLambda
    events:
      - http:
          path: /internal
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  createUser:
    handler: web-api/${self:provider.dir}/usersHandlers.createUserLambda
    events:
      - http:
          path: /
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  getCasesByUser:
    handler: web-api/${self:provider.dir}/usersHandlers.getCasesByUserLambda
    events:
      - http:
          path: /{userId}/cases
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  getConsolidatedCasesByUser:
    handler: web-api/${self:provider.dir}/usersHandlers.getConsolidatedCasesByUserLambda
    events:
      - http:
          path: /{userId}/cases-with-consolidation
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  verifyPendingCaseForUser:
    handler: web-api/${self:provider.dir}/usersHandlers.verifyPendingCaseForUserLambda
    events:
      - http:
          path: /{userId}/case/{caseId}/pending
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  practitionerCaseAssociation:
    handler: web-api/${self:provider.dir}/usersHandlers.practitionerCaseAssociationLambda
    events:
      - http:
          path: /{userId}/case/{caseId}
          method: put
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  practitionerPendingCaseAssociation:
    handler: web-api/${self:provider.dir}/usersHandlers.practitionerPendingCaseAssociationLambda
    events:
      - http:
          path: /{userId}/case/{caseId}/pending
          method: put
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  getInboxMessagesForUser:
    handler: web-api/${self:provider.dir}/usersHandlers.getInboxMessagesForUserLambda
    events:
      - http:
          path: /{userId}/messages/inbox
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  getSentMessagesForUser:
    handler: web-api/${self:provider.dir}/usersHandlers.getSentMessagesForUserLambda
    events:
      - http:
          path: /{userId}/messages/sent
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  getDocumentQCInboxForUser:
    handler: web-api/${self:provider.dir}/usersHandlers.getDocumentQCInboxForUserLambda
    events:
      - http:
          path: /{userId}/document-qc/inbox
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  getDocumentQCBatchedForUser:
    handler: web-api/${self:provider.dir}/usersHandlers.getDocumentQCBatchedForUserLambda
    events:
      - http:
          path: /{userId}/document-qc/batched
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  getDocumentQCServedForUser:
    handler: web-api/${self:provider.dir}/usersHandlers.getDocumentQCServedForUserLambda
    events:
      - http:
          path: /{userId}/document-qc/served
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  updateUserContactInformation:
    handler: web-api/${self:provider.dir}/usersHandlers.updateUserContactInformationLambda
    layers:
      - arn:aws:lambda:${opt:region}:${opt:accountId}:layer:${opt:stage}-puppeteer:latest
    memorySize: 3008
    timeout: 900
    events:
      - http:
          path: /{userId}/contact-info
          method: put
          cors: true
          async: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  getPractitionersBySearchKey:
    handler: web-api/${self:provider.dir}/usersHandlers.getPractitionersBySearchKeyLambda
    events:
      - http:
          path: /practitioners/search
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  getRespondentsBySearchKey:
    handler: web-api/${self:provider.dir}/usersHandlers.getRespondentsBySearchKeyLambda
    events:
      - http:
          path: /respondents/search
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
