
FROM node:8-alpine

RUN apk add --no-cache --update bash
RUN apk add --no-cache --update git

ENV AWS_CLI_VERSION 1.16.31

RUN apk --no-cache update && \
    apk --no-cache add python py-pip py-setuptools ca-certificates groff less && \
    apk --no-cache add bash git openssh && \
    pip install --upgrade pip && \
    pip --no-cache-dir install awscli==${AWS_CLI_VERSION} && \
    rm -rf /var/cache/apk/*

WORKDIR /home/app

COPY . /home/app

CMD ./setup-s3-replication.sh $ENV