FROM node:8-alpine

RUN apk add git

WORKDIR /home/app

COPY business/package.json /home/app/business/package.json
RUN cd /home/app/business; npm install

COPY efcms-service/package.json /home/app/efcms-service/package.json
RUN cd /home/app/efcms-service; npm install

COPY . /home/app

WORKDIR /home/app/efcms-service

CMD npm test