FROM node:8-alpine

RUN apk add git

WORKDIR /home/app

COPY efcms-service/package.json /home/app/package.json
RUN cd /home/app/efcms-service; npm install
COPY business/package.json /home/app/package.json
RUN cd /home/app/business; npm install

COPY . /home/app

WORKDIR /home/app/efcms-service

CMD npm test