name: Node.js CI - Api

on:
  pull_request:
  push:
    branches:
      - dependency-updates
      - test

jobs:
  API:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: NPM Install
        run: npm ci --legacy-peer-deps
      - name: API
        run: npm run test:api
