name: Node.js CI - scripts

on:
  pull_request:
  push:
    branches:
      - dependency-updates
      - test

jobs:
  Scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Scripts
        run: |
          npm ci --legacy-peer-deps
          npm run test:scripts
