import { Get } from 'cerebral';
import {
  AMENDMENT_EVENT_CODES,
  INTERNAL_DOCUMENT_TYPES_REQUIRING_OBJECTION,
  INTERNAL_DOCUMENTS_ARRAY,
  NOTICE_OF_CHANGE_CONTACT_INFORMATION_EVENT_CODES,
} from '@shared/business/entities/EntityConstants';
import { getOptionsForCategory } from './selectDocumentTypeHelper';
import { state } from '@web-client/presenter/app.cerebral';
import { DocketEntry } from '@shared/business/entities/DocketEntry';

export const getSupportingDocumentTypeList = categoryMap => {
  return categoryMap['Supporting Document'].map(entry => {
    const entryCopy = { ...entry }; //to prevent against modifying constants
    entryCopy.documentTypeDisplay = entryCopy.documentType.replace(
      /\sin\sSupport$/i,
      '',
    );
    return entryCopy;
  });
};

export const addDocketEntryHelper = (
  get: Get,
): {
  primary: any;
  secondary: any;
  showDateReceivedEdit: boolean;
  showFilingPartiesForm: boolean;
  showObjection: boolean;
  showTrackOption: boolean;
} => {
  const user = get(state.user);
  const caseDetail = get(state.caseDetail);
  if (!caseDetail.partyType) {
    return {
      primary: undefined,
      secondary: undefined,
      showDateReceivedEdit: false,
      showFilingPartiesForm: false,
      showObjection: false,
      showTrackOption: false,
    };
  }
  const showDateReceivedEdit = !!caseDetail.isPaper;
  const form = get(state.form);

  const selectedEventCode = form.eventCode;
  const secondarySelectedEventCode = get(
    state.form.secondaryDocument.eventCode,
  );

  const categoryInformation = INTERNAL_DOCUMENTS_ARRAY.find(
    d => d.eventCode === selectedEventCode,
  );
  const secondaryCategoryInformation = INTERNAL_DOCUMENTS_ARRAY.find(
    d => d.eventCode === secondarySelectedEventCode,
  );

  const selectedDocketEntryId = get(state.docketEntryId);

  const optionsForCategory = getOptionsForCategory({
    caseDetail,
    categoryInformation,
    selectedDocketEntryId,
    authorizedUser: user,
  });

  const secondaryOptionsForCategory = getOptionsForCategory({
    caseDetail,
    categoryInformation: secondaryCategoryInformation,
    selectedDocketEntryId,
    authorizedUser: user,
  });

  if (optionsForCategory.showSecondaryDocumentSelect) {
    optionsForCategory.showSecondaryDocumentSelect = false;
    optionsForCategory.showSecondaryDocumentForm = true;
  }

  const showTrackOption = !DocketEntry.isPendingOnCreation(form);

  const isSystemGeneratedNoticeOfChangeOfAddress =
    NOTICE_OF_CHANGE_CONTACT_INFORMATION_EVENT_CODES.includes(form.eventCode) &&
    form.isAutoGenerated;
  const showFilingPartiesForm = !isSystemGeneratedNoticeOfChangeOfAddress;

  const showObjection =
    INTERNAL_DOCUMENT_TYPES_REQUIRING_OBJECTION.has(form.documentType) ||
    (AMENDMENT_EVENT_CODES.includes(form.eventCode) &&
      INTERNAL_DOCUMENT_TYPES_REQUIRING_OBJECTION.has(
        form.previousDocument?.documentType,
      ));

  return {
    primary: optionsForCategory,
    secondary: secondaryOptionsForCategory,
    showDateReceivedEdit,
    showFilingPartiesForm,
    showObjection,
    showTrackOption,
  };
};
