import { runCompute } from '@web-client/presenter/test.cerebral';
import { fileAutoGeneratedDocumentReviewHelper } from './fileAutoGeneratedDocumentReviewHelper';

describe('fileAutoGeneratedDocumentReviewHelper', () => {
  it('should return formatted parties based on the filersMap and caseDetail', () => {
    const result = runCompute(fileAutoGeneratedDocumentReviewHelper, {
      state: {
        form: {
          filersMap: {
            '1': true,
            '2': false,
            '3': true,
          },
        },
        caseDetail: {
          petitioners: [
            { contactId: '1', name: 'John Doe', contactType: 'petitioner' },
            { contactId: '2', name: 'Jane Smith', contactType: 'intervenor' },
            { contactId: '3', name: 'Humpty', contactType: 'participant' },
          ],
        },
      },
    });

    expect(result.formattedParties).toEqual([
      'John Doe, Petitioner',
      'Humpty, Participant',
    ]);
  });
});
