import { Case } from '@shared/business/entities/cases/Case';
import { ClientApplicationContext } from '@web-client/applicationContext';
import {
  EXPLICITLY_DENIED_CONSOLIDATED_GROUP_FILING_EVENT_CODES,
  EXTERNAL_DOCUMENT_TYPES_REQUIRING_OBJECTION,
  ROLES,
  SERVICE_INDICATOR_TYPES,
} from '@shared/business/entities/EntityConstants';
import { GENERATION_TYPES } from '@web-client/getConstants';
import { Get } from 'cerebral';
import { getFilerParties } from './getFilerParties';
import { getSupportingDocumentTypeList } from './addDocketEntryHelper';
import { showGenerationType } from '@web-client/presenter/actions/setDefaultGenerationTypeAction';
import { state } from '@web-client/presenter/app.cerebral';
import { EXTERNAL_FILING_EVENTS } from '@shared/business/entities/docketEntry/externalFilingEvents';

export const supportingDocumentFreeTextTypes = [
  'Affidavit in Support',
  'Declaration in Support',
  'Unsworn Declaration under Penalty of Perjury in Support',
];

const SUPPORTING_DOCUMENTS_MAX_COUNT = 5;

export const fileDocumentHelper = (
  get: Get,
  applicationContext: ClientApplicationContext,
): any => {
  const { AMENDMENT_EVENT_CODES, PARTY_TYPES } =
    applicationContext.getConstants();
  const caseDetail = get(state.caseDetail);
  const form = get(state.form);
  const validationErrors = get(state.validationErrors);
  const user = get(state.user);

  const supportingDocumentTypeList = getSupportingDocumentTypeList(
    EXTERNAL_FILING_EVENTS,
  );

  const partyValidationError =
    validationErrors.filers || validationErrors.partyIrsPractitioner;

  const { certificateOfServiceDate } = form;
  let certificateOfServiceDateFormatted;
  if (certificateOfServiceDate) {
    certificateOfServiceDateFormatted = applicationContext
      .getUtilities()
      .formatDateString(certificateOfServiceDate, 'MMDDYY');
  }

  const secondaryDocumentCertificateOfServiceDate =
    form.secondaryDocument && form.secondaryDocument.certificateOfServiceDate;
  let secondaryDocumentCertificateOfServiceDateFormatted;
  if (secondaryDocumentCertificateOfServiceDate) {
    secondaryDocumentCertificateOfServiceDateFormatted = applicationContext
      .getUtilities()
      .formatDateString(secondaryDocumentCertificateOfServiceDate, 'MMDDYY');
  }

  const isInConsolidatedGroup = !!caseDetail.leadDocketNumber;
  const isMultiDocketableEventCode = !!applicationContext
    .getConstants()
    .MULTI_DOCKET_FILING_EVENT_CODES.includes(form.eventCode);
  const isAllowedToFileInConsolidatedGroup = () => {
    if (
      EXPLICITLY_DENIED_CONSOLIDATED_GROUP_FILING_EVENT_CODES.includes(
        form.eventCode,
      )
    ) {
      return !(
        user.role === ROLES.privatePractitioner ||
        user.role === ROLES.irsPractitioner
      );
    }
    return true;
  };
  let allowExternalConsolidatedGroupFiling = false;
  if (
    isMultiDocketableEventCode &&
    isInConsolidatedGroup &&
    isAllowedToFileInConsolidatedGroup()
  ) {
    allowExternalConsolidatedGroupFiling = true;
  } else {
    allowExternalConsolidatedGroupFiling = false;
  }

  const showFilingIncludes = form.certificateOfService || form.attachments;

  const supportingDocumentFlags = getSupportingDocumentFlags(form);

  const { primaryDocument, secondaryDocument } = getPrimarySecondaryDocuments({
    AMENDMENT_EVENT_CODES,
    form,
  });
  secondaryDocument.certificateOfServiceDateFormatted =
    secondaryDocumentCertificateOfServiceDateFormatted;

  const showSecondaryProperties = getShowSecondaryProperties({
    PARTY_TYPES,
    caseDetail,
    form,
  });

  const parties = form.filersMap;

  const formattedFilingParties = getFilerParties({
    caseDetail,
    filersMap: parties,
  });

  const EARedactionAcknowledgement =
    form.generationType === GENERATION_TYPES.MANUAL && form.eventCode === 'EA';

  const showGenerationTypeForm = showGenerationType(
    user,
    form.eventCode,
    caseDetail.petitioners,
  );

  const showPartiesFiling =
    user.role !== ROLES.irsPractitioner || !Case.isFirstIrsFiling(caseDetail);

  const isAutoGenerated = form.generationType === GENERATION_TYPES.AUTO;

  const showNoticeOfWithdrawal = getShowNoticeOfWithdrawal(form);

  let partiesHeaderText = 'Parties Filing The Document(s)';
  let partiesLabelText = 'Filing Parties';
  const shouldUsePartyToWithdrawFrom =
    form.eventCode === 'NOTW' &&
    (user.role === ROLES.privatePractitioner ||
      user.role === ROLES.irsPractitioner);
  if (shouldUsePartyToWithdrawFrom) {
    partiesHeaderText = "Parties You're Withdrawing From as Counsel";
    partiesLabelText = 'Parties';
  }

  const showApplicableCOSText = caseDetail.petitioners.some(
    p => p.serviceIndicator === SERVICE_INDICATOR_TYPES.SI_PAPER,
  );

  const exported = {
    EARedactionAcknowledgement,
    allowExternalConsolidatedGroupFiling,
    certificateOfServiceDateFormatted,
    formattedFilingParties,
    isAutoGenerated,
    isSecondaryDocumentUploadOptional:
      form.documentType === 'Motion for Leave to File',
    partiesHeaderText,
    partiesLabelText,
    partyValidationError,
    primaryDocument,
    secondaryDocument,
    showApplicableCOSText,
    showFilingIncludes,
    showGenerationTypeForm,
    showNoticeOfWithdrawal,
    showPartiesFiling,
    showPrimaryDocumentValid: !!form.primaryDocumentFile,
    supportingDocumentTypeList,
    ...showSecondaryProperties,
    ...supportingDocumentFlags,
    docketNumber: caseDetail.docketNumber,
  };

  if (form.hasSupportingDocuments) {
    const supportingDocuments = (form.supportingDocuments || []).map(item =>
      getFormattedSupportingDocument({ applicationContext, item }),
    );
    Object.assign(exported, { supportingDocuments });
  }

  if (form.hasSecondarySupportingDocuments) {
    const secondarySupportingDocuments = (
      form.secondarySupportingDocuments || []
    ).map(item => getFormattedSupportingDocument({ applicationContext, item }));
    Object.assign(exported, { secondarySupportingDocuments });
  }

  return exported;
};

const getSupportingDocumentFlags = form => {
  const supportingDocumentCount =
    (form.supportingDocuments && form.supportingDocuments.length) || 0;
  const showAddSupportingDocuments =
    !supportingDocumentCount ||
    supportingDocumentCount < SUPPORTING_DOCUMENTS_MAX_COUNT;
  const showAddSupportingDocumentsLimitReached = !!(
    supportingDocumentCount &&
    supportingDocumentCount >= SUPPORTING_DOCUMENTS_MAX_COUNT
  );

  const secondarySupportingDocumentCount =
    (form.secondarySupportingDocuments &&
      form.secondarySupportingDocuments.length) ||
    0;
  const showAddSecondarySupportingDocuments =
    (!secondarySupportingDocumentCount ||
      secondarySupportingDocumentCount < SUPPORTING_DOCUMENTS_MAX_COUNT) &&
    (form.documentType !== 'Motion for Leave to File' ||
      !!form.secondaryDocumentFile);
  const showAddSecondarySupportingDocumentsLimitReached = !!(
    secondarySupportingDocumentCount &&
    secondarySupportingDocumentCount >= SUPPORTING_DOCUMENTS_MAX_COUNT
  );
  return {
    showAddSecondarySupportingDocuments,
    showAddSecondarySupportingDocumentsLimitReached,
    showAddSupportingDocuments,
    showAddSupportingDocumentsLimitReached,
  };
};

const getShowSecondaryProperties = ({ caseDetail, form, PARTY_TYPES }) => {
  const showSecondaryParty = [
    PARTY_TYPES.petitionerSpouse,
    PARTY_TYPES.petitionerDeceasedSpouse,
  ].includes(caseDetail.partyType);

  const showSecondaryFilingIncludes =
    form.secondaryDocument &&
    (form.secondaryDocument.certificateOfService ||
      form.secondaryDocument.attachments);

  const showSecondaryDocumentInclusionsForm =
    form.documentType !== 'Motion for Leave to File' ||
    !!form.secondaryDocumentFile;

  return {
    showSecondaryDocument:
      form.secondaryDocument && form.secondaryDocument.documentTitle,
    showSecondaryDocumentInclusionsForm,
    showSecondaryDocumentValid: !!form.secondaryDocumentFile,
    showSecondaryFilingIncludes,
    showSecondaryParty,
    showSecondarySupportingDocumentValid: !!form.supportingDocumentFile,
  };
};

const getShowNoticeOfWithdrawal = form => {
  return form.eventCode === 'NOTW';
};

const getPrimarySecondaryDocuments = ({ AMENDMENT_EVENT_CODES, form }) => {
  const primarySecondaryDocuments: {
    primaryDocument: { showObjection: boolean };
    secondaryDocument: {
      showObjection: boolean;
      certificateOfServiceDateFormatted?: string;
    };
  } = {
    primaryDocument: {
      showObjection:
        EXTERNAL_DOCUMENT_TYPES_REQUIRING_OBJECTION.has(form.documentType) ||
        (AMENDMENT_EVENT_CODES.includes(form.eventCode) &&
          EXTERNAL_DOCUMENT_TYPES_REQUIRING_OBJECTION.has(
            form.previousDocument?.documentType,
          )),
    },
    secondaryDocument: {
      showObjection:
        form.secondaryDocument &&
        form.secondaryDocumentFile &&
        (EXTERNAL_DOCUMENT_TYPES_REQUIRING_OBJECTION.has(
          form.secondaryDocument.documentType,
        ) ||
          (AMENDMENT_EVENT_CODES.includes(form.secondaryDocument.eventCode) &&
            EXTERNAL_DOCUMENT_TYPES_REQUIRING_OBJECTION.has(
              form.secondaryDocument.previousDocument?.documentType,
            ))),
    },
  };
  return primarySecondaryDocuments;
};

const getFormattedSupportingDocument = ({ applicationContext, item }) => {
  let certificateOfServiceDateFormatted;

  if (item.certificateOfServiceDate) {
    certificateOfServiceDateFormatted = applicationContext
      .getUtilities()
      .formatDateString(item.certificateOfServiceDate, 'MMDDYY');
  }
  return {
    certificateOfServiceDateFormatted,
    showFilingIncludes: item.certificateOfService || item.attachments,
    showSupportingDocumentFreeText:
      item.supportingDocument &&
      supportingDocumentFreeTextTypes.includes(item.supportingDocument),
    showSupportingDocumentUpload:
      item.supportingDocument && item.supportingDocument !== '',
    showSupportingDocumentValid: !!item.supportingDocumentFile,
  };
};
