import { MOCK_CASE } from '../../../../shared/src/test/mockCase';
import { applicationContext } from '../../applicationContext';
import { runCompute } from '@web-client/presenter/test.cerebral';
import { trialSessionWorkingCopyHelper as trialSessionWorkingCopyHelperComputed } from './trialSessionWorkingCopyHelper';
import { withAppContextDecorator } from '../../withAppContext';

describe('trial session working copy computed', () => {
  const trialSessionWorkingCopyHelper = withAppContextDecorator(
    trialSessionWorkingCopyHelperComputed,
    applicationContext,
  );

  const MOCK_TRIAL_SESSION = {
    city: 'Hartford',
    courtReporter: 'Test Court Reporter',
    irsCalendarAdministrator: 'Test Calendar Admin',
    judge: { name: 'Test Judge' },
    postalCode: '12345',
    startDate: '2019-11-25T15:00:00.000Z',
    startTime: '10:00',
    state: 'CT',
    term: 'Fall',
    termYear: '2019',
    trialClerk: { name: 'Test Trial Clerk' },
    trialLocation: 'Hartford, Connecticut',
  };

  describe.only('formattedcases', () => {
    it('should output corrected formatted cases', () => {
      const { formattedCases } = runCompute(trialSessionWorkingCopyHelper, {
        state: {
          trialSession: {
            ...MOCK_TRIAL_SESSION,
            calendaredCases: [
              MOCK_CASE,
              {
                ...MOCK_CASE,
                docketNumber: '102-19',
                leadDocketNumber: '500-17',
                privatePractitioners: [],
              },
              {
                ...MOCK_CASE,
                docketNumber: '5000-17',
                leadDocketNumber: '500-17',
                privatePractitioners: [{}, {}],
              },
              {
                ...MOCK_CASE,
                consolidatedCases: [
                  { docketNumber: '102-19' },
                  { docketNumber: '5000-17' },
                ],
                docketNumber: '500-17',
                leadDocketNumber: '500-17',
                privatePractitioners: [{}, {}],
              },
              {
                ...MOCK_CASE,
                docketNumber: '90-07',
              },
            ],
            caseOrder: [],
          },
          trialSessionWorkingCopy: {
            caseMetadata: {},
            filters: { statusUnassigned: true },
            sort: 'practitioner',
            sortOrder: 'asc',
            userNotes: {},
          },
        },
      });

      expect(formattedCases).toEqual([
        {
          archivedDocketEntries: [],
          caseCaption: 'Test Petitioner, Petitioner',
          caseTitle: 'Test Petitioner',
          caseType: 'Other',
          consolidatedCases: [],
          correspondence: [],
          createdAt: '2018-03-01T21:40:46.415Z',
          docketEntries: [
            {
              createdAt: '2018-11-21T20:49:28.192Z',
              docketEntryId: '9de27a7d-7c6b-434b-803b-7655f82d5e07',
              docketNumber: '101-18',
              documentTitle: 'Petition',
              documentType: 'Petition',
              draftOrderState: {},
              entityName: 'DocketEntry',
              eventCode: 'P',
              filedBy: 'Test Petitioner',
              filedByRole: 'petitioner',
              filers: [],
              filingDate: '2018-03-01T05:00:00.000Z',
              index: 1,
              isFileAttached: true,
              isMinuteEntry: false,
              isOnDocketRecord: true,
              pending: false,
              processingStatus: 'complete',
              receivedAt: '2018-03-01T05:00:00.000Z',
              stampData: {},
              userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
            },
            {
              createdAt: '2018-11-21T20:49:28.192Z',
              docketEntryId: 'abc81f4d-1e47-423a-8caf-6d2fdc3d3859',
              docketNumber: '101-18',
              documentTitle: 'Statement of Taxpayer Identification',
              documentType: 'Statement of Taxpayer Identification',
              draftOrderState: {},
              entityName: 'DocketEntry',
              eventCode: 'STIN',
              filedByRole: 'petitioner',
              filers: [],
              filingDate: '2018-03-01T05:00:00.000Z',
              index: 3,
              isFileAttached: true,
              isMinuteEntry: false,
              isOnDocketRecord: false,
              pending: false,
              processingStatus: 'complete',
              receivedAt: '2018-03-01T05:00:00.000Z',
              stampData: {},
              userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
            },
            {
              createdAt: '2018-11-21T20:49:28.192Z',
              docketEntryId: 'e6b81f4d-1e47-423a-8caf-6d2fdc3d3859',
              docketNumber: '101-18',
              documentTitle: 'Answer',
              documentType: 'Answer',
              draftOrderState: {},
              entityName: 'DocketEntry',
              eventCode: 'A',
              filedBy: 'Test Petitioner',
              filedByRole: 'petitioner',
              filers: [],
              filingDate: '2018-03-01T05:00:00.000Z',
              index: 4,
              isFileAttached: true,
              isMinuteEntry: false,
              isOnDocketRecord: false,
              pending: false,
              processingStatus: 'complete',
              receivedAt: '2018-03-01T05:00:00.000Z',
              servedAt: '2019-08-25T05:00:00.000Z',
              servedParties: [
                {
                  name: 'Bernard Lowe',
                },
                {
                  name: 'IRS',
                  role: 'irsSuperuser',
                },
              ],
              stampData: {},
              userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
            },
            {
              createdAt: '2018-11-21T20:49:28.192Z',
              docketEntryId: 'def81f4d-1e47-423a-8caf-6d2fdc3d3859',
              docketNumber: '101-18',
              documentTitle: 'Proposed Stipulated Decision',
              documentType: 'Proposed Stipulated Decision',
              draftOrderState: {},
              entityName: 'DocketEntry',
              eventCode: 'PSDE',
              filedBy: 'Test Petitioner',
              filedByRole: 'petitioner',
              filers: [],
              filingDate: '2018-03-01T05:00:00.000Z',
              index: 5,
              isFileAttached: true,
              isMinuteEntry: false,
              isOnDocketRecord: false,
              pending: true,
              processingStatus: 'pending',
              receivedAt: '2018-03-01T05:00:00.000Z',
              servedAt: '2019-08-25T05:00:00.000Z',
              servedParties: [
                {
                  name: 'Bernard Lowe',
                },
                {
                  name: 'IRS',
                  role: 'irsSuperuser',
                },
              ],
              stampData: {},
              userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
            },
          ],
          docketNumber: '90-07',
          docketNumberWithSuffix: '101-18',
          entityName: 'Case',
          filingType: 'Myself',
          hasVerifiedIrsNotice: false,
          hearings: [],
          inConsolidatedGroup: false,
          irsNoticeDate: '2018-03-01T00:00:00.000Z',
          irsPractitioners: [],
          isDocketSuffixHighPriority: false,
          isLeadCase: false,
          partyType: 'Petitioner',
          petitionPaymentStatus: 'Not paid',
          petitioners: [
            {
              address1: '123 Main St',
              city: 'Somewhere',
              contactId: '7805d1ab-18d0-43ec-bafb-654e83405416',
              contactType: 'primary',
              countryType: 'domestic',
              email: 'petitioner@example.com',
              entityName: 'Petitioner',
              isAddressSealed: false,
              name: 'Test Petitioner',
              phone: '1234567',
              postalCode: '12345',
              sealedAndUnavailable: false,
              serviceIndicator: 'Electronic',
              state: 'TN',
              title: 'Executor',
            },
          ],
          preferredTrialCity: 'Washington, District of Columbia',
          privatePractitioners: [],
          procedureType: 'Regular',
          receivedAt: '2018-03-01T21:40:46.415Z',
          sortableDocketNumber: 2018000101,
          status: 'New',
        },
        {
          archivedDocketEntries: [],
          caseCaption: 'Test Petitioner, Petitioner',
          caseTitle: 'Test Petitioner',
          caseType: 'Other',
          consolidatedCases: [],
          correspondence: [],
          createdAt: '2018-03-01T21:40:46.415Z',
          docketEntries: [
            {
              createdAt: '2018-11-21T20:49:28.192Z',
              docketEntryId: '9de27a7d-7c6b-434b-803b-7655f82d5e07',
              docketNumber: '101-18',
              documentTitle: 'Petition',
              documentType: 'Petition',
              draftOrderState: {},
              entityName: 'DocketEntry',
              eventCode: 'P',
              filedBy: 'Test Petitioner',
              filedByRole: 'petitioner',
              filers: [],
              filingDate: '2018-03-01T05:00:00.000Z',
              index: 1,
              isFileAttached: true,
              isMinuteEntry: false,
              isOnDocketRecord: true,
              pending: false,
              processingStatus: 'complete',
              receivedAt: '2018-03-01T05:00:00.000Z',
              stampData: {},
              userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
            },
            {
              createdAt: '2018-11-21T20:49:28.192Z',
              docketEntryId: 'abc81f4d-1e47-423a-8caf-6d2fdc3d3859',
              docketNumber: '101-18',
              documentTitle: 'Statement of Taxpayer Identification',
              documentType: 'Statement of Taxpayer Identification',
              draftOrderState: {},
              entityName: 'DocketEntry',
              eventCode: 'STIN',
              filedByRole: 'petitioner',
              filers: [],
              filingDate: '2018-03-01T05:00:00.000Z',
              index: 3,
              isFileAttached: true,
              isMinuteEntry: false,
              isOnDocketRecord: false,
              pending: false,
              processingStatus: 'complete',
              receivedAt: '2018-03-01T05:00:00.000Z',
              stampData: {},
              userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
            },
            {
              createdAt: '2018-11-21T20:49:28.192Z',
              docketEntryId: 'e6b81f4d-1e47-423a-8caf-6d2fdc3d3859',
              docketNumber: '101-18',
              documentTitle: 'Answer',
              documentType: 'Answer',
              draftOrderState: {},
              entityName: 'DocketEntry',
              eventCode: 'A',
              filedBy: 'Test Petitioner',
              filedByRole: 'petitioner',
              filers: [],
              filingDate: '2018-03-01T05:00:00.000Z',
              index: 4,
              isFileAttached: true,
              isMinuteEntry: false,
              isOnDocketRecord: false,
              pending: false,
              processingStatus: 'complete',
              receivedAt: '2018-03-01T05:00:00.000Z',
              servedAt: '2019-08-25T05:00:00.000Z',
              servedParties: [
                {
                  name: 'Bernard Lowe',
                },
                {
                  name: 'IRS',
                  role: 'irsSuperuser',
                },
              ],
              stampData: {},
              userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
            },
            {
              createdAt: '2018-11-21T20:49:28.192Z',
              docketEntryId: 'def81f4d-1e47-423a-8caf-6d2fdc3d3859',
              docketNumber: '101-18',
              documentTitle: 'Proposed Stipulated Decision',
              documentType: 'Proposed Stipulated Decision',
              draftOrderState: {},
              entityName: 'DocketEntry',
              eventCode: 'PSDE',
              filedBy: 'Test Petitioner',
              filedByRole: 'petitioner',
              filers: [],
              filingDate: '2018-03-01T05:00:00.000Z',
              index: 5,
              isFileAttached: true,
              isMinuteEntry: false,
              isOnDocketRecord: false,
              pending: true,
              processingStatus: 'pending',
              receivedAt: '2018-03-01T05:00:00.000Z',
              servedAt: '2019-08-25T05:00:00.000Z',
              servedParties: [
                {
                  name: 'Bernard Lowe',
                },
                {
                  name: 'IRS',
                  role: 'irsSuperuser',
                },
              ],
              stampData: {},
              userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
            },
          ],
          docketNumber: '101-18',
          docketNumberWithSuffix: '101-18',
          entityName: 'Case',
          filingType: 'Myself',
          hasVerifiedIrsNotice: false,
          hearings: [],
          inConsolidatedGroup: false,
          irsNoticeDate: '2018-03-01T00:00:00.000Z',
          irsPractitioners: [],
          isDocketSuffixHighPriority: false,
          isLeadCase: false,
          partyType: 'Petitioner',
          petitionPaymentStatus: 'Not paid',
          petitioners: [
            {
              address1: '123 Main St',
              city: 'Somewhere',
              contactId: '7805d1ab-18d0-43ec-bafb-654e83405416',
              contactType: 'primary',
              countryType: 'domestic',
              email: 'petitioner@example.com',
              entityName: 'Petitioner',
              isAddressSealed: false,
              name: 'Test Petitioner',
              phone: '1234567',
              postalCode: '12345',
              sealedAndUnavailable: false,
              serviceIndicator: 'Electronic',
              state: 'TN',
              title: 'Executor',
            },
          ],
          preferredTrialCity: 'Washington, District of Columbia',
          privatePractitioners: [],
          procedureType: 'Regular',
          receivedAt: '2018-03-01T21:40:46.415Z',
          sortableDocketNumber: 2018000101,
          status: 'New',
        },
        {
          archivedDocketEntries: [],
          caseCaption: 'Test Petitioner, Petitioner',
          caseTitle: 'Test Petitioner',
          caseType: 'Other',
          consolidatedCases: [],
          consolidatedIconTooltipText: 'Lead case',
          correspondence: [],
          createdAt: '2018-03-01T21:40:46.415Z',
          docketEntries: [
            {
              createdAt: '2018-11-21T20:49:28.192Z',
              docketEntryId: '9de27a7d-7c6b-434b-803b-7655f82d5e07',
              docketNumber: '101-18',
              documentTitle: 'Petition',
              documentType: 'Petition',
              draftOrderState: {},
              entityName: 'DocketEntry',
              eventCode: 'P',
              filedBy: 'Test Petitioner',
              filedByRole: 'petitioner',
              filers: [],
              filingDate: '2018-03-01T05:00:00.000Z',
              index: 1,
              isFileAttached: true,
              isMinuteEntry: false,
              isOnDocketRecord: true,
              pending: false,
              processingStatus: 'complete',
              receivedAt: '2018-03-01T05:00:00.000Z',
              stampData: {},
              userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
            },
            {
              createdAt: '2018-11-21T20:49:28.192Z',
              docketEntryId: 'abc81f4d-1e47-423a-8caf-6d2fdc3d3859',
              docketNumber: '101-18',
              documentTitle: 'Statement of Taxpayer Identification',
              documentType: 'Statement of Taxpayer Identification',
              draftOrderState: {},
              entityName: 'DocketEntry',
              eventCode: 'STIN',
              filedByRole: 'petitioner',
              filers: [],
              filingDate: '2018-03-01T05:00:00.000Z',
              index: 3,
              isFileAttached: true,
              isMinuteEntry: false,
              isOnDocketRecord: false,
              pending: false,
              processingStatus: 'complete',
              receivedAt: '2018-03-01T05:00:00.000Z',
              stampData: {},
              userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
            },
            {
              createdAt: '2018-11-21T20:49:28.192Z',
              docketEntryId: 'e6b81f4d-1e47-423a-8caf-6d2fdc3d3859',
              docketNumber: '101-18',
              documentTitle: 'Answer',
              documentType: 'Answer',
              draftOrderState: {},
              entityName: 'DocketEntry',
              eventCode: 'A',
              filedBy: 'Test Petitioner',
              filedByRole: 'petitioner',
              filers: [],
              filingDate: '2018-03-01T05:00:00.000Z',
              index: 4,
              isFileAttached: true,
              isMinuteEntry: false,
              isOnDocketRecord: false,
              pending: false,
              processingStatus: 'complete',
              receivedAt: '2018-03-01T05:00:00.000Z',
              servedAt: '2019-08-25T05:00:00.000Z',
              servedParties: [
                {
                  name: 'Bernard Lowe',
                },
                {
                  name: 'IRS',
                  role: 'irsSuperuser',
                },
              ],
              stampData: {},
              userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
            },
            {
              createdAt: '2018-11-21T20:49:28.192Z',
              docketEntryId: 'def81f4d-1e47-423a-8caf-6d2fdc3d3859',
              docketNumber: '101-18',
              documentTitle: 'Proposed Stipulated Decision',
              documentType: 'Proposed Stipulated Decision',
              draftOrderState: {},
              entityName: 'DocketEntry',
              eventCode: 'PSDE',
              filedBy: 'Test Petitioner',
              filedByRole: 'petitioner',
              filers: [],
              filingDate: '2018-03-01T05:00:00.000Z',
              index: 5,
              isFileAttached: true,
              isMinuteEntry: false,
              isOnDocketRecord: false,
              pending: true,
              processingStatus: 'pending',
              receivedAt: '2018-03-01T05:00:00.000Z',
              servedAt: '2019-08-25T05:00:00.000Z',
              servedParties: [
                {
                  name: 'Bernard Lowe',
                },
                {
                  name: 'IRS',
                  role: 'irsSuperuser',
                },
              ],
              stampData: {},
              userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
            },
          ],
          docketNumber: '500-17',
          docketNumberWithSuffix: '101-18',
          entityName: 'Case',
          filingType: 'Myself',
          hasVerifiedIrsNotice: false,
          hearings: [],
          inConsolidatedGroup: true,
          irsNoticeDate: '2018-03-01T00:00:00.000Z',
          irsPractitioners: [],
          isDocketSuffixHighPriority: false,
          isLeadCase: true,
          leadDocketNumber: '500-17',
          nestedConsolidatedCases: [
            {
              archivedDocketEntries: [],
              caseCaption: 'Test Petitioner, Petitioner',
              caseTitle: 'Test Petitioner',
              caseType: 'Other',
              consolidatedCases: [],
              consolidatedIconTooltipText: 'Consolidated case',
              correspondence: [],
              createdAt: '2018-03-01T21:40:46.415Z',
              docketEntries: [
                {
                  createdAt: '2018-11-21T20:49:28.192Z',
                  docketEntryId: '9de27a7d-7c6b-434b-803b-7655f82d5e07',
                  docketNumber: '101-18',
                  documentTitle: 'Petition',
                  documentType: 'Petition',
                  draftOrderState: {},
                  entityName: 'DocketEntry',
                  eventCode: 'P',
                  filedBy: 'Test Petitioner',
                  filedByRole: 'petitioner',
                  filers: [],
                  filingDate: '2018-03-01T05:00:00.000Z',
                  index: 1,
                  isFileAttached: true,
                  isMinuteEntry: false,
                  isOnDocketRecord: true,
                  pending: false,
                  processingStatus: 'complete',
                  receivedAt: '2018-03-01T05:00:00.000Z',
                  stampData: {},
                  userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
                },
                {
                  createdAt: '2018-11-21T20:49:28.192Z',
                  docketEntryId: 'abc81f4d-1e47-423a-8caf-6d2fdc3d3859',
                  docketNumber: '101-18',
                  documentTitle: 'Statement of Taxpayer Identification',
                  documentType: 'Statement of Taxpayer Identification',
                  draftOrderState: {},
                  entityName: 'DocketEntry',
                  eventCode: 'STIN',
                  filedByRole: 'petitioner',
                  filers: [],
                  filingDate: '2018-03-01T05:00:00.000Z',
                  index: 3,
                  isFileAttached: true,
                  isMinuteEntry: false,
                  isOnDocketRecord: false,
                  pending: false,
                  processingStatus: 'complete',
                  receivedAt: '2018-03-01T05:00:00.000Z',
                  stampData: {},
                  userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
                },
                {
                  createdAt: '2018-11-21T20:49:28.192Z',
                  docketEntryId: 'e6b81f4d-1e47-423a-8caf-6d2fdc3d3859',
                  docketNumber: '101-18',
                  documentTitle: 'Answer',
                  documentType: 'Answer',
                  draftOrderState: {},
                  entityName: 'DocketEntry',
                  eventCode: 'A',
                  filedBy: 'Test Petitioner',
                  filedByRole: 'petitioner',
                  filers: [],
                  filingDate: '2018-03-01T05:00:00.000Z',
                  index: 4,
                  isFileAttached: true,
                  isMinuteEntry: false,
                  isOnDocketRecord: false,
                  pending: false,
                  processingStatus: 'complete',
                  receivedAt: '2018-03-01T05:00:00.000Z',
                  servedAt: '2019-08-25T05:00:00.000Z',
                  servedParties: [
                    {
                      name: 'Bernard Lowe',
                    },
                    {
                      name: 'IRS',
                      role: 'irsSuperuser',
                    },
                  ],
                  stampData: {},
                  userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
                },
                {
                  createdAt: '2018-11-21T20:49:28.192Z',
                  docketEntryId: 'def81f4d-1e47-423a-8caf-6d2fdc3d3859',
                  docketNumber: '101-18',
                  documentTitle: 'Proposed Stipulated Decision',
                  documentType: 'Proposed Stipulated Decision',
                  draftOrderState: {},
                  entityName: 'DocketEntry',
                  eventCode: 'PSDE',
                  filedBy: 'Test Petitioner',
                  filedByRole: 'petitioner',
                  filers: [],
                  filingDate: '2018-03-01T05:00:00.000Z',
                  index: 5,
                  isFileAttached: true,
                  isMinuteEntry: false,
                  isOnDocketRecord: false,
                  pending: true,
                  processingStatus: 'pending',
                  receivedAt: '2018-03-01T05:00:00.000Z',
                  servedAt: '2019-08-25T05:00:00.000Z',
                  servedParties: [
                    {
                      name: 'Bernard Lowe',
                    },
                    {
                      name: 'IRS',
                      role: 'irsSuperuser',
                    },
                  ],
                  stampData: {},
                  userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
                },
              ],
              docketNumber: '5000-17',
              docketNumberWithSuffix: '101-18',
              entityName: 'Case',
              filingType: 'Myself',
              hasVerifiedIrsNotice: false,
              hearings: [],
              inConsolidatedGroup: true,
              irsNoticeDate: '2018-03-01T00:00:00.000Z',
              irsPractitioners: [],
              isDocketSuffixHighPriority: false,
              isLeadCase: false,
              leadDocketNumber: '500-17',
              partyType: 'Petitioner',
              petitionPaymentStatus: 'Not paid',
              petitioners: [
                {
                  address1: '123 Main St',
                  city: 'Somewhere',
                  contactId: '7805d1ab-18d0-43ec-bafb-654e83405416',
                  contactType: 'primary',
                  countryType: 'domestic',
                  email: 'petitioner@example.com',
                  entityName: 'Petitioner',
                  isAddressSealed: false,
                  name: 'Test Petitioner',
                  phone: '1234567',
                  postalCode: '12345',
                  sealedAndUnavailable: false,
                  serviceIndicator: 'Electronic',
                  state: 'TN',
                  title: 'Executor',
                },
              ],
              preferredTrialCity: 'Washington, District of Columbia',
              privatePractitioners: [{}, {}],
              procedureType: 'Regular',
              receivedAt: '2018-03-01T21:40:46.415Z',
              sortableDocketNumber: 2018000101,
              status: 'New',
            },
            {
              archivedDocketEntries: [],
              caseCaption: 'Test Petitioner, Petitioner',
              caseTitle: 'Test Petitioner',
              caseType: 'Other',
              consolidatedCases: [],
              consolidatedIconTooltipText: 'Consolidated case',
              correspondence: [],
              createdAt: '2018-03-01T21:40:46.415Z',
              docketEntries: [
                {
                  createdAt: '2018-11-21T20:49:28.192Z',
                  docketEntryId: '9de27a7d-7c6b-434b-803b-7655f82d5e07',
                  docketNumber: '101-18',
                  documentTitle: 'Petition',
                  documentType: 'Petition',
                  draftOrderState: {},
                  entityName: 'DocketEntry',
                  eventCode: 'P',
                  filedBy: 'Test Petitioner',
                  filedByRole: 'petitioner',
                  filers: [],
                  filingDate: '2018-03-01T05:00:00.000Z',
                  index: 1,
                  isFileAttached: true,
                  isMinuteEntry: false,
                  isOnDocketRecord: true,
                  pending: false,
                  processingStatus: 'complete',
                  receivedAt: '2018-03-01T05:00:00.000Z',
                  stampData: {},
                  userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
                },
                {
                  createdAt: '2018-11-21T20:49:28.192Z',
                  docketEntryId: 'abc81f4d-1e47-423a-8caf-6d2fdc3d3859',
                  docketNumber: '101-18',
                  documentTitle: 'Statement of Taxpayer Identification',
                  documentType: 'Statement of Taxpayer Identification',
                  draftOrderState: {},
                  entityName: 'DocketEntry',
                  eventCode: 'STIN',
                  filedByRole: 'petitioner',
                  filers: [],
                  filingDate: '2018-03-01T05:00:00.000Z',
                  index: 3,
                  isFileAttached: true,
                  isMinuteEntry: false,
                  isOnDocketRecord: false,
                  pending: false,
                  processingStatus: 'complete',
                  receivedAt: '2018-03-01T05:00:00.000Z',
                  stampData: {},
                  userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
                },
                {
                  createdAt: '2018-11-21T20:49:28.192Z',
                  docketEntryId: 'e6b81f4d-1e47-423a-8caf-6d2fdc3d3859',
                  docketNumber: '101-18',
                  documentTitle: 'Answer',
                  documentType: 'Answer',
                  draftOrderState: {},
                  entityName: 'DocketEntry',
                  eventCode: 'A',
                  filedBy: 'Test Petitioner',
                  filedByRole: 'petitioner',
                  filers: [],
                  filingDate: '2018-03-01T05:00:00.000Z',
                  index: 4,
                  isFileAttached: true,
                  isMinuteEntry: false,
                  isOnDocketRecord: false,
                  pending: false,
                  processingStatus: 'complete',
                  receivedAt: '2018-03-01T05:00:00.000Z',
                  servedAt: '2019-08-25T05:00:00.000Z',
                  servedParties: [
                    {
                      name: 'Bernard Lowe',
                    },
                    {
                      name: 'IRS',
                      role: 'irsSuperuser',
                    },
                  ],
                  stampData: {},
                  userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
                },
                {
                  createdAt: '2018-11-21T20:49:28.192Z',
                  docketEntryId: 'def81f4d-1e47-423a-8caf-6d2fdc3d3859',
                  docketNumber: '101-18',
                  documentTitle: 'Proposed Stipulated Decision',
                  documentType: 'Proposed Stipulated Decision',
                  draftOrderState: {},
                  entityName: 'DocketEntry',
                  eventCode: 'PSDE',
                  filedBy: 'Test Petitioner',
                  filedByRole: 'petitioner',
                  filers: [],
                  filingDate: '2018-03-01T05:00:00.000Z',
                  index: 5,
                  isFileAttached: true,
                  isMinuteEntry: false,
                  isOnDocketRecord: false,
                  pending: true,
                  processingStatus: 'pending',
                  receivedAt: '2018-03-01T05:00:00.000Z',
                  servedAt: '2019-08-25T05:00:00.000Z',
                  servedParties: [
                    {
                      name: 'Bernard Lowe',
                    },
                    {
                      name: 'IRS',
                      role: 'irsSuperuser',
                    },
                  ],
                  stampData: {},
                  userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
                },
              ],
              docketNumber: '102-19',
              docketNumberWithSuffix: '101-18',
              entityName: 'Case',
              filingType: 'Myself',
              hasVerifiedIrsNotice: false,
              hearings: [],
              inConsolidatedGroup: true,
              irsNoticeDate: '2018-03-01T00:00:00.000Z',
              irsPractitioners: [],
              isDocketSuffixHighPriority: false,
              isLeadCase: false,
              leadDocketNumber: '500-17',
              partyType: 'Petitioner',
              petitionPaymentStatus: 'Not paid',
              petitioners: [
                {
                  address1: '123 Main St',
                  city: 'Somewhere',
                  contactId: '7805d1ab-18d0-43ec-bafb-654e83405416',
                  contactType: 'primary',
                  countryType: 'domestic',
                  email: 'petitioner@example.com',
                  entityName: 'Petitioner',
                  isAddressSealed: false,
                  name: 'Test Petitioner',
                  phone: '1234567',
                  postalCode: '12345',
                  sealedAndUnavailable: false,
                  serviceIndicator: 'Electronic',
                  state: 'TN',
                  title: 'Executor',
                },
              ],
              preferredTrialCity: 'Washington, District of Columbia',
              privatePractitioners: [],
              procedureType: 'Regular',
              receivedAt: '2018-03-01T21:40:46.415Z',
              sortableDocketNumber: 2018000101,
              status: 'New',
            },
          ],
          partyType: 'Petitioner',
          petitionPaymentStatus: 'Not paid',
          petitioners: [
            {
              address1: '123 Main St',
              city: 'Somewhere',
              contactId: '7805d1ab-18d0-43ec-bafb-654e83405416',
              contactType: 'primary',
              countryType: 'domestic',
              email: 'petitioner@example.com',
              entityName: 'Petitioner',
              isAddressSealed: false,
              name: 'Test Petitioner',
              phone: '1234567',
              postalCode: '12345',
              sealedAndUnavailable: false,
              serviceIndicator: 'Electronic',
              state: 'TN',
              title: 'Executor',
            },
          ],
          preferredTrialCity: 'Washington, District of Columbia',
          privatePractitioners: [{}, {}],
          procedureType: 'Regular',
          receivedAt: '2018-03-01T21:40:46.415Z',
          sortableDocketNumber: 2018000101,
          status: 'New',
        },
      ]);
    });
  });

  describe('sorting', () => {
    it('should sort cases by docket number ascending when sort is set to "docket" and sortOrder is "asc"', () => {
      const { formattedCases } = runCompute(trialSessionWorkingCopyHelper, {
        state: {
          trialSession: {
            ...MOCK_TRIAL_SESSION,
            calendaredCases: [
              MOCK_CASE,
              { ...MOCK_CASE, docketNumber: '102-19' },
              { ...MOCK_CASE, docketNumber: '5000-17' },
              { ...MOCK_CASE, docketNumber: '500-17' },
              { ...MOCK_CASE, docketNumber: '90-07' },
            ],
            caseOrder: [],
          },
          trialSessionWorkingCopy: {
            caseMetadata: {},
            filters: { statusUnassigned: true },
            sort: 'docket',
            sortOrder: 'asc',
            userNotes: {},
          },
        },
      });

      expect(formattedCases).toMatchObject([
        { docketNumber: '90-07' },
        { docketNumber: '500-17' },
        { docketNumber: '5000-17' },
        { docketNumber: '101-18' },
        { docketNumber: '102-19' },
      ]);
    });

    it('should sort cases by docket number descending when sort is set to "docket" and sortOrder is "desc"', () => {
      const { formattedCases } = runCompute(trialSessionWorkingCopyHelper, {
        state: {
          trialSession: {
            ...MOCK_TRIAL_SESSION,
            calendaredCases: [
              MOCK_CASE,
              { ...MOCK_CASE, docketNumber: '102-19' },
              { ...MOCK_CASE, docketNumber: '5000-17' },
              { ...MOCK_CASE, docketNumber: '500-17' },
              { ...MOCK_CASE, docketNumber: '90-07' },
            ],
            caseOrder: [],
          },
          trialSessionWorkingCopy: {
            caseMetadata: {},
            filters: { statusUnassigned: true },
            sort: 'docket',
            sortOrder: 'desc',
            userNotes: {},
          },
        },
      });

      expect(formattedCases).toMatchObject([
        { docketNumber: '102-19' },
        { docketNumber: '101-18' },
        { docketNumber: '5000-17' },
        { docketNumber: '500-17' },
        { docketNumber: '90-07' },
      ]);
    });

    it('should sort cases by private practitioner count ascending when sort is set to "practitioner" and sortOrder is "asc"', () => {
      const { casesShownCount, formattedCases } = runCompute(
        trialSessionWorkingCopyHelper,
        {
          state: {
            trialSession: {
              ...MOCK_TRIAL_SESSION,
              calendaredCases: [
                MOCK_CASE,
                {
                  ...MOCK_CASE,
                  docketNumber: '102-19',
                  privatePractitioners: [],
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '5000-17',
                  privatePractitioners: [{}, {}],
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '500-17',
                  privatePractitioners: [{}, {}],
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '90-07',
                },
              ],
              caseOrder: [],
            },
            trialSessionWorkingCopy: {
              caseMetadata: {},
              filters: { statusUnassigned: true },
              sort: 'practitioner',
              sortOrder: 'asc',
              userNotes: {},
            },
          },
        },
      );

      expect(formattedCases).toMatchObject([
        { docketNumber: '90-07' },
        { docketNumber: '101-18' },
        { docketNumber: '102-19' },
        { docketNumber: '500-17' },
        { docketNumber: '5000-17' },
      ]);
      expect(casesShownCount).toEqual(5);
    });

    it('should sort only lead and unconsolidated cases, but return the total number of cases as casesShownCount', () => {
      const { casesShownCount, formattedCases } = runCompute(
        trialSessionWorkingCopyHelper,
        {
          state: {
            trialSession: {
              ...MOCK_TRIAL_SESSION,
              calendaredCases: [
                MOCK_CASE,
                {
                  ...MOCK_CASE,
                  docketNumber: '102-19',
                  leadDocketNumber: '500-17',
                  privatePractitioners: [],
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '5000-17',
                  leadDocketNumber: '500-17',
                  privatePractitioners: [{}, {}],
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '500-17',
                  leadDocketNumber: '500-17',
                  privatePractitioners: [{}, {}],
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '90-07',
                },
              ],
              caseOrder: [],
            },
            trialSessionWorkingCopy: {
              caseMetadata: {},
              filters: { statusUnassigned: true },
              sort: 'practitioner',
              sortOrder: 'asc',
              userNotes: {},
            },
          },
        },
      );

      expect(formattedCases).toMatchObject([
        { docketNumber: '90-07' },
        { docketNumber: '101-18' },
        { docketNumber: '500-17' },
      ]);
      expect(casesShownCount).toEqual(5);
    });

    it('should return lead and unconsolidated cases, and sort consolidated cases within a lead case in ascending order', () => {
      const { casesShownCount, formattedCases } = runCompute(
        trialSessionWorkingCopyHelper,
        {
          state: {
            trialSession: {
              ...MOCK_TRIAL_SESSION,
              calendaredCases: [
                MOCK_CASE,
                {
                  ...MOCK_CASE,
                  docketNumber: '102-19',
                  leadDocketNumber: '500-17',
                  privatePractitioners: [],
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '5000-17',
                  leadDocketNumber: '500-17',
                  privatePractitioners: [{}, {}],
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '500-17',
                  leadDocketNumber: '500-17',
                  privatePractitioners: [{}, {}],
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '90-18',
                  leadDocketNumber: '500-17',
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '101-21',
                  leadDocketNumber: '500-17',
                  privatePractitioners: [],
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '115-20',
                  privatePractitioners: [],
                },
              ],
              caseOrder: [],
            },
            trialSessionWorkingCopy: {
              caseMetadata: {},
              filters: { statusUnassigned: true },
              sort: 'docket',
              sortOrder: 'asc',
              userNotes: {},
            },
          },
        },
      );

      expect(formattedCases).toMatchObject([
        { docketNumber: '500-17' },
        { docketNumber: '101-18' },
        { docketNumber: '115-20' },
      ]);
      expect(formattedCases[0].consolidatedCases).toMatchObject([
        { docketNumber: '5000-17' },
        { docketNumber: '90-18' },
        { docketNumber: '102-19' },
        { docketNumber: '101-21' },
      ]);
      expect(casesShownCount).toEqual(7);
    });

    it('should return a member case (without a lead case on the trial session) and unconsolidated cases', () => {
      const { formattedCases } = runCompute(trialSessionWorkingCopyHelper, {
        state: {
          trialSession: {
            ...MOCK_TRIAL_SESSION,
            calendaredCases: [
              {
                ...MOCK_CASE,
                docketNumber: '102-19',
                leadDocketNumber: '500-17',
                privatePractitioners: [],
              },
              {
                ...MOCK_CASE,
                docketNumber: '115-20',
                privatePractitioners: [],
              },
            ],
            caseOrder: [],
          },
          trialSessionWorkingCopy: {
            caseMetadata: {},
            filters: { statusUnassigned: true },
            sort: 'docket',
            sortOrder: 'asc',
            userNotes: {},
          },
        },
      });

      expect(formattedCases).toMatchObject([
        { docketNumber: '102-19' },
        { docketNumber: '115-20' },
      ]);
    });

    it('should return a member case (without a lead case on the trial session), a lead case, and unconsolidated cases sorted in ascending order', () => {
      const { formattedCases } = runCompute(trialSessionWorkingCopyHelper, {
        state: {
          trialSession: {
            ...MOCK_TRIAL_SESSION,
            calendaredCases: [
              {
                ...MOCK_CASE,
                docketNumber: '102-19',
                leadDocketNumber: '500-17',
                privatePractitioners: [],
              },
              {
                ...MOCK_CASE,
                docketNumber: '111-17',
                leadDocketNumber: '111-17',
                privatePractitioners: [],
              },
              {
                ...MOCK_CASE,
                docketNumber: '122-17',
                leadDocketNumber: '111-17',
                privatePractitioners: [],
              },
              {
                ...MOCK_CASE,
                docketNumber: '115-20',
                privatePractitioners: [],
              },
            ],
            caseOrder: [],
          },
          trialSessionWorkingCopy: {
            caseMetadata: {},
            filters: { statusUnassigned: true },
            sort: 'docket',
            sortOrder: 'asc',
            userNotes: {},
          },
        },
      });

      expect(formattedCases).toMatchObject([
        { docketNumber: '111-17' },
        { docketNumber: '102-19' },
        { docketNumber: '115-20' },
      ]);

      expect(formattedCases[0].consolidatedCases).toMatchObject([
        { docketNumber: '122-17' },
      ]);
    });

    it('should assign consolidated member cases to the correct lead case and sort them correctly', () => {
      const { casesShownCount, formattedCases } = runCompute(
        trialSessionWorkingCopyHelper,
        {
          state: {
            trialSession: {
              ...MOCK_TRIAL_SESSION,
              calendaredCases: [
                {
                  ...MOCK_CASE,
                  docketNumber: '102-19',
                  leadDocketNumber: '90-18',
                  privatePractitioners: [],
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '5000-17',
                  leadDocketNumber: '500-17',
                  privatePractitioners: [{}, {}],
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '500-17',
                  leadDocketNumber: '500-17',
                  privatePractitioners: [{}, {}],
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '90-18',
                  leadDocketNumber: '90-18',
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '101-21',
                  leadDocketNumber: '116-20',
                  privatePractitioners: [],
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '116-20',
                  leadDocketNumber: '116-20',
                  privatePractitioners: [],
                },
                {
                  ...MOCK_CASE,
                  docketNumber: '111-22',
                  leadDocketNumber: '500-17',
                  privatePractitioners: [],
                },
              ],
              caseOrder: [],
            },
            trialSessionWorkingCopy: {
              caseMetadata: {},
              filters: { statusUnassigned: true },
              sort: 'docket',
              sortOrder: 'desc',
              userNotes: {},
            },
          },
        },
      );

      expect(formattedCases).toMatchObject([
        { docketNumber: '116-20' },
        { docketNumber: '90-18' },
        { docketNumber: '500-17' },
      ]);
      expect(formattedCases[0].consolidatedCases).toMatchObject([
        { docketNumber: '101-21' },
      ]);
      expect(formattedCases[1].consolidatedCases).toMatchObject([
        { docketNumber: '102-19' },
      ]);
      expect(formattedCases[2].consolidatedCases).toMatchObject([
        { docketNumber: '5000-17' },
        { docketNumber: '111-22' },
      ]);
      expect(casesShownCount).toEqual(7);
    });
  });
});
