import { PETITION_TYPES } from '@web-client/presenter/actions/setupPetitionStateAction';
import { getCaseCaptionMeta } from '@shared/business/utilities/getCaseCaptionMeta';
import { state } from '@web-client/presenter/app.cerebral';

export const generatePetitionPdfAction = async ({
  applicationContext,
  get,
}: ActionProps) => {
  const { petitionType } = get(state.form);

  if (petitionType === PETITION_TYPES.autoGenerated) {
    const form = get(state.form);
    const caseCaption =
      applicationContext
        .getUtilities()
        .getCaseCaption({ ...form, petitioners: [] }) || '';

    const { caseCaptionExtension, caseTitle } = getCaseCaptionMeta({
      caseCaption,
    });

    const docketNumberWithSuffix = '9999-99';

    const {
      caseType,
      contactPrimary,
      contactSecondary,
      petitionFacts,
      petitionReasons,
      preferredTrialCity,
      procedureType,
    } = form;

    // This will either be duplicated when we actually create the case, or it should be moved
    const user = applicationContext.getCurrentUser();
    contactPrimary.email = user.email;

    // Why aren't these values set?
    const noticeIssuedDate = '01/01/99';
    const taxYear = '1999';

    const { url } = await applicationContext
      .getUseCases()
      .generatePetitionPdfInteractor(applicationContext, {
        caseCaptionExtension,
        caseTitle,
        caseType,
        contactPrimary,
        contactSecondary,
        docketNumberWithSuffix,
        noticeIssuedDate,
        petitionFacts,
        petitionReasons,
        preferredTrialCity,
        procedureType,
        taxYear,
      });

    return { pdfUrl: url };
  }
};
