const {
  aggregatePartiesForService,
} = require('../../utilities/aggregatePartiesForService');
const {
  DocketEntry,
  getServedPartiesCode,
} = require('../../entities/DocketEntry');
const {
  DOCUMENT_PROCESSING_STATUS_OPTIONS,
} = require('../../entities/EntityConstants');
const { createISODateString } = require('../../utilities/DateHandler');

/**
 * createAndServeNoticeDocketEntry
 *
 * @param {object} applicationContext the application context
 * @param {object} providers the providers object
 * @param {object} providers.caseEntity the case data
 * @param {object} providers.documentInfo information on the document being served
 * @param {object} providers.newPdfDoc the new PDF contents to be appended
 * @param {object} providers.noticePdf the notice pdf being served
 * @param {object} providers.userId the user ID
 */
exports.createAndServeNoticeDocketEntry = async (
  applicationContext,
  {
    additionalDocketEntryInfo = {},
    caseEntity,
    documentInfo,
    newPdfDoc,
    noticePdf,
    userId,
  },
) => {
  const docketEntryId = applicationContext.getUniqueId();

  await applicationContext.getPersistenceGateway().saveDocumentFromLambda({
    applicationContext,
    document: noticePdf,
    key: docketEntryId,
  });

  const servedParties = aggregatePartiesForService(caseEntity);

  const numberOfPages = await applicationContext
    .getUseCaseHelpers()
    .countPagesInDocument({
      applicationContext,
      docketEntryId,
    });

  const noticeDocketEntry = new DocketEntry(
    {
      docketEntryId,
      documentTitle: documentInfo.documentTitle,
      documentType: documentInfo.documentType,
      eventCode: documentInfo.eventCode,
      isAutoGenerated: true,
      isFileAttached: true,
      isOnDocketRecord: true,
      numberOfPages,
      processingStatus: DOCUMENT_PROCESSING_STATUS_OPTIONS.COMPLETE,
      servedAt: createISODateString(),
      servedParties: servedParties.all,
      servedPartiesCode: getServedPartiesCode(servedParties.all),
      userId,
      ...additionalDocketEntryInfo,
    },
    { applicationContext },
  );

  caseEntity.addDocketEntry(noticeDocketEntry);

  await applicationContext.getUseCaseHelpers().serveGeneratedNoticesOnCase({
    applicationContext,
    caseEntity,
    newPdfDoc,
    noticeDocketEntryEntity: noticeDocketEntry,
    noticeDocumentPdfData: noticePdf,
    servedParties,
  });
};
