exports.userMap = {
  docketclerk: {
    'custom:role': 'docketclerk',
    email: 'docketclerk@example.com',
    name: 'Test Docketclerk',
    role: 'docketclerk',
    userId: '1805d1ab-18d0-43ec-bafb-654e83405416',
  },
  docketclerk1: {
    'custom:role': 'docketclerk',
    email: 'docketclerk1@example.com',
    name: 'Test Docketclerk1',
    role: 'docketclerk',
    userId: '2805d1ab-18d0-43ec-bafb-654e83405416',
  },

  judgeArmen: {
    'custom:role': 'judge',
    email: 'judgeArmen',
    name: 'Judge Armen',
    role: 'judge',
    userId: 'dabbad00-18d0-43ec-bafb-654e83405416',
  },
  judgeAshford: {
    'custom:role': 'judge',
    email: 'judgeAshford',
    name: 'Judge Ashford',
    role: 'judge',
    userId: 'dabbad01-18d0-43ec-bafb-654e83405416',
  },
  judgeBuch: {
    'custom:role': 'judge',
    email: 'judgeBuch',
    name: 'Judge Buch',
    role: 'judge',
    userId: 'dabbad02-18d0-43ec-bafb-654e83405416',
  },
  judgeCarluzzo: {
    'custom:role': 'judge',
    email: 'judgeCarluzzo',
    name: 'Judge Carluzzo',
    role: 'judge',
    userId: 'dabbad03-18d0-43ec-bafb-654e83405416',
  },
  judgeCohen: {
    'custom:role': 'judge',
    email: 'judgeCohen',
    name: 'Judge Cohen',
    role: 'judge',
    userId: 'dabbad04-18d0-43ec-bafb-654e83405416',
  },

  petitionsclerk: {
    'custom:role': 'petitionsclerk',
    email: 'petitionsclerk@example.com',
    name: 'Test Petitionsclerk',
    role: 'petitionsclerk',
    userId: '3805d1ab-18d0-43ec-bafb-654e83405416',
  },
  petitionsclerk1: {
    'custom:role': 'petitionsclerk',
    email: 'petitionsclerk1@example.com',
    name: 'Test Petitionsclerk1',
    role: 'petitionsclerk',
    userId: '4805d1ab-18d0-43ec-bafb-654e83405416',
  },
  practitioner: {
    barNumber: 'PT1234',
    contact: {
      addressLine1: '234 Main St',
      addressLine2: 'Apartment 4',
      addressLine3: 'Under the stairs',
      city: 'Chicago',
      countryType: 'domestic',
      phone: '+1 (555) 555-5555',
      postalCode: '61234',
      state: 'IL',
    },
    'custom:role': 'practitioner',
    email: 'practitioner@example.com',
    name: 'Test Practitioner',
    role: 'practitioner',
    userId: '9805d1ab-18d0-43ec-bafb-654e83405416',
  },
  practitioner1: {
    barNumber: 'PT5432',
    contact: {
      addressLine1: '234 Main St',
      addressLine2: 'Apartment 4',
      addressLine3: 'Under the stairs',
      city: 'Chicago',
      countryType: 'domestic',
      phone: '+1 (555) 555-5555',
      postalCode: '61234',
      state: 'IL',
    },
    'custom:role': 'practitioner',
    email: 'practitioner1@example.com',
    name: 'Test Practitioner1',
    role: 'practitioner',
    userId: 'ad07b846-8933-4778-9fe2-b5d8ac8ad728',
  },
  practitioner2: {
    barNumber: 'GL1111',
    contact: {
      addressLine1: '234 Main St',
      addressLine2: 'Apartment 4',
      addressLine3: 'Under the stairs',
      city: 'Chicago',
      countryType: 'domestic',
      phone: '+1 (555) 555-5555',
      postalCode: '61234',
      state: 'IL',
    },
    'custom:role': 'practitioner',
    email: 'practitioner2@example.com',
    name: 'Lilah Gilbert',
    role: 'practitioner',
    userId: '8e4959cd-3e13-4bf6-95bf-a276cc63b9e1',
  },
  practitioner3: {
    barNumber: 'SC2222',
    contact: {
      addressLine1: '234 Main St',
      addressLine2: 'Apartment 4',
      addressLine3: 'Under the stairs',
      city: 'Chicago',
      countryType: 'domestic',
      phone: '+1 (555) 555-5555',
      postalCode: '61234',
      state: 'IL',
    },
    'custom:role': 'practitioner',
    email: 'practitioner3@example.com',
    name: 'Clark Stark',
    role: 'practitioner',
    userId: '9f25dc2c-764a-435c-86dd-323e53634537',
  },
  practitioner4: {
    barNumber: 'RA3333',
    contact: {
      addressLine1: '234 Main St',
      addressLine2: 'Apartment 4',
      addressLine3: 'Under the stairs',
      city: 'Chicago',
      countryType: 'domestic',
      phone: '+1 (555) 555-5555',
      postalCode: '61234',
      state: 'IL',
    },
    'custom:role': 'practitioner',
    email: 'practitioner4@example.com',
    name: 'Alden Rivas',
    role: 'practitioner',
    userId: '29e9b4d1-63bc-4f66-b230-59a3a9ae44eb',
  },
  respondent: {
    barNumber: 'RT6789',
    contact: {
      addressLine1: '234 Main St',
      addressLine2: 'Apartment 4',
      addressLine3: 'Under the stairs',
      city: 'Chicago',
      countryType: 'domestic',
      phone: '+1 (555) 555-5555',
      postalCode: '61234',
      state: 'IL',
    },
    'custom:role': 'respondent',
    email: 'respondent@example.com',
    name: 'Test Respondent',
    role: 'respondent',
    userId: '5805d1ab-18d0-43ec-bafb-654e83405416',
  },
  respondent1: {
    barNumber: 'RT0987',
    contact: {
      addressLine1: '234 Main St',
      addressLine2: 'Apartment 4',
      addressLine3: 'Under the stairs',
      city: 'Chicago',
      countryType: 'domestic',
      phone: '+1 (555) 555-5555',
      postalCode: '61234',
      state: 'IL',
    },
    'custom:role': 'respondent',
    email: 'respondent1@example.com',
    name: 'Test Respondent1',
    role: 'respondent',
    userId: '5fb6e815-b5d3-459b-b08b-49c61f0fce5e',
  },
  respondent2: {
    barNumber: 'WN7777',
    contact: {
      addressLine1: '234 Main St',
      addressLine2: 'Apartment 4',
      addressLine3: 'Under the stairs',
      city: 'Chicago',
      countryType: 'domestic',
      phone: '+1 (555) 555-5555',
      postalCode: '61234',
      state: 'IL',
    },
    'custom:role': 'respondent',
    email: 'respondent2@example.com',
    name: 'Nero West',
    role: 'respondent',
    userId: '2d9a7229-7d5a-459f-84ad-754504a9f10f',
  },
  respondent3: {
    barNumber: 'MS8888',
    contact: {
      addressLine1: '234 Main St',
      addressLine2: 'Apartment 4',
      addressLine3: 'Under the stairs',
      city: 'Chicago',
      countryType: 'domestic',
      phone: '+1 (555) 555-5555',
      postalCode: '61234',
      state: 'IL',
    },
    'custom:role': 'respondent',
    email: 'respondent3@example.com',
    name: 'Stuart Morrison',
    role: 'respondent',
    userId: '5c43a30d-9c3d-41be-ad13-3b6d7cef54fc',
  },
  respondent4: {
    barNumber: 'LJ9999',
    contact: {
      addressLine1: '234 Main St',
      addressLine2: 'Apartment 4',
      addressLine3: 'Under the stairs',
      city: 'Chicago',
      countryType: 'domestic',
      phone: '+1 (555) 555-5555',
      postalCode: '61234',
      state: 'IL',
    },
    'custom:role': 'respondent',
    email: 'respondent4@example.com',
    name: 'Jaquelyn Lane',
    role: 'respondent',
    userId: '726c38b1-1432-49b3-9383-77a998c0ba4f',
  },
  seniorattorney: {
    'custom:role': 'seniorattorney',
    email: 'seniorattorney@example.com',
    name: 'Test Seniorattorney',
    role: 'seniorattorney',
    userId: '6805d1ab-18d0-43ec-bafb-654e83405416',
  },
  taxpayer: {
    'custom:role': 'petitioner',
    email: 'taxpayer@example.com',
    name: 'Test Petitioner',
    role: 'petitioner',
    userId: '7805d1ab-18d0-43ec-bafb-654e83405416',
  },
};

const client = require('../../dynamodbClientService');

/**
 * getUserById
 *
 * @param {string} userId the id of the user
 * @returns {*} result returned from persistence
 */
exports.getUserById = async ({ applicationContext, userId }) => {
  return client.get({
    Key: {
      pk: userId,
      sk: userId,
    },
    applicationContext,
  });
};
