import { AuthUser } from '@shared/business/entities/authUser/AuthUser';
import {
  DOCKET_SECTION,
  DOCUMENT_PROCESSING_STATUS_OPTIONS,
  ROLES,
  SERVICE_INDICATOR_TYPES,
} from '../../../../../shared/src/business/entities/EntityConstants';
import { DocketEntry } from '../../../../../shared/src/business/entities/DocketEntry';
import { ServerApplicationContext } from '@web-api/applicationContext';
import { WorkItem } from '../../../../../shared/src/business/entities/WorkItem';
import { addCoverToPdf } from '../../useCases/addCoverToPdf';
import { getCaseCaptionMeta } from '../../../../../shared/src/business/utilities/getCaseCaptionMeta';
import { upsertWorkItems } from '@web-api/persistence/postgres/workitems/upsertWorkItems';
import { Case } from '@shared/business/entities/cases/Case';
import {
  formattedNewEmailForChangeOfAddress,
  formattedOldEmailForChangeOfAddress,
} from '@shared/business/utilities/calculateEmail';

/**
 * This function isolates task of generating the Docket Entry
 *
 * @param {object} providers the providers object
 * @param {object} providers.applicationContext the application context
 * @param {object} providers.caseEntity the instantiated Case class (updated by reference)
 * @param {object} providers.documentType the document type of the document being created
 * @param {object} providers.newData the new contact information
 * @param {object} providers.oldData the old contact information (for comparison)
 * @param {object} providers.user the user object that includes userId, barNumber etc.
 * @returns {Promise<User[]>} the internal users
 */
const createDocketEntryForChange = async ({
  applicationContext,
  authorizedUser,
  caseEntity,
  docketMeta = {},
  documentType,
  newData,
  oldData,
  servedParties,
  user,
}: {
  applicationContext: any;
  caseEntity: any;
  docketMeta: any;
  documentType: any;
  newData: any;
  oldData: any;
  servedParties: any;
  user: any;
  authorizedUser: AuthUser;
}) => {
  const caseDetail = caseEntity.validate().toRawObject();
  const { caseCaptionExtension, caseTitle } = getCaseCaptionMeta(caseDetail);
  let changeOfAddressPdfName = newData.name;
  let contactName = newData.name;

  // should only be true when called via generateChangeOfAddress
  if (
    user.role === ROLES.privatePractitioner ||
    user.role === ROLES.irsPractitioner
  ) {
    changeOfAddressPdfName = changeOfAddressPdfName + ` (${user.barNumber})`;
    contactName = newData.name;
  }

  const isAddressSealed =
    caseEntity.petitioners.find(
      petitioner =>
        petitioner.email === newData.email && petitioner.name === newData.name,
    )?.isAddressSealed ?? false;

  oldData.email = formattedOldEmailForChangeOfAddress(
    oldData.email,
    isAddressSealed,
  );
  newData.email = formattedNewEmailForChangeOfAddress(
    newData.email,
    isAddressSealed,
  );

  applicationContext.logger.info(
    `Starting generating change of address document for case ${caseEntity.docketNumber}`,
  );

  const changeOfAddressPdf = await applicationContext
    .getDocumentGenerators()
    .changeOfAddress({
      applicationContext,
      content: {
        caseCaptionExtension,
        caseTitle,
        docketNumber: caseEntity.docketNumber,
        docketNumberWithSuffix: caseEntity.docketNumberWithSuffix,
        documentType,
        name: changeOfAddressPdfName,
        newData,
        oldData,
      },
    });

  applicationContext.logger.info(
    `Finished generating change of address document for case ${caseEntity.docketNumber}`,
  );

  const newDocumentStorageId = applicationContext.getUniqueId();

  const changeOfAddressDocketEntry = new DocketEntry(
    {
      addToCoversheet: true,
      additionalInfo: `for ${contactName}`,
      docketEntryId: newDocumentStorageId,
      documentStorageId: newDocumentStorageId,
      docketNumber: caseEntity.docketNumber,
      documentTitle: documentType.title,
      documentType: documentType.title,
      eventCode: documentType.eventCode,
      isAutoGenerated: true,
      isFileAttached: true,
      isOnDocketRecord: true,
      processingStatus: DOCUMENT_PROCESSING_STATUS_OPTIONS.COMPLETE,
      ...docketMeta,
    },
    { authorizedUser },
  );

  changeOfAddressDocketEntry.setFiledBy(user);

  caseEntity.addDocketEntry(changeOfAddressDocketEntry);

  applicationContext.logger.info(
    `Starting add cover to pdf for case ${caseEntity.docketNumber}`,
  );

  const { pdfData: changeOfAddressPdfWithCover } = await addCoverToPdf({
    applicationContext,
    caseEntity,
    docketEntryEntity: changeOfAddressDocketEntry,
    pdfData: changeOfAddressPdf,
  });

  applicationContext.logger.info(
    `Finished add cover to pdf for case ${caseEntity.docketNumber}`,
  );

  applicationContext.logger.info(
    `Starting counting pages for case ${caseEntity.docketNumber}`,
  );

  changeOfAddressDocketEntry.numberOfPages = await applicationContext
    .getUseCaseHelpers()
    .countPagesInDocument({
      applicationContext,
      documentBytes: changeOfAddressPdfWithCover,
    });

  applicationContext.logger.info(
    `Finished counting pages for case ${caseEntity.docketNumber}`,
  );

  changeOfAddressDocketEntry.setAsServed(servedParties.all);

  applicationContext.logger.info(
    `Starting save document to S3 for case ${caseEntity.docketNumber} (docket entry id ${newDocumentStorageId})`,
  );

  await applicationContext.getPersistenceGateway().saveDocumentFromLambda({
    document: changeOfAddressPdfWithCover,
    key: newDocumentStorageId,
  });

  applicationContext.logger.info(
    `Finished save document to S3 for case ${caseEntity.docketNumber} (docket entry id ${newDocumentStorageId})`,
  );

  applicationContext.logger.info(
    `Starting get download policy url for case ${caseEntity.docketNumber}`,
  );
  const { url } = await applicationContext
    .getPersistenceGateway()
    .getDownloadPolicyUrl({
      applicationContext,
      key: newDocumentStorageId,
    });

  applicationContext.logger.info(
    `Finished get download policy url for case ${caseEntity.docketNumber}`,
  );

  return {
    changeOfAddressDocketEntry,
    changeOfAddressPdfWithCover,
    servedParties,
    url,
  };
};

const createWorkItemForChange = async ({
  applicationContext,
  caseEntity,
  changeOfAddressDocketEntry,
  user,
}: {
  applicationContext: ServerApplicationContext;
  caseEntity: any;
  changeOfAddressDocketEntry: any;
  user: any;
}) => {
  applicationContext.logger.info(
    `Starting upsert work item for change of address for case ${caseEntity.docketNumber}`,
  );

  const workItem = new WorkItem({
    assigneeId: null,
    assigneeName: null,
    docketEntryId: changeOfAddressDocketEntry.docketEntryId,
    docketNumber: caseEntity.docketNumber,
    section: DOCKET_SECTION,
    sentBy: user.name,
    sentByUserId: user.userId,
  });

  await upsertWorkItems({
    workItems: [workItem.validate().toRawObject()],
  });

  applicationContext.logger.info(
    `Finished upsert work item for change of address for case ${caseEntity.docketNumber}`,
  );
};

export const generateAndServeDocketEntry = async ({
  applicationContext,
  authorizedUser,
  caseEntity,
  docketMeta,
  documentType,
  newData,
  oldData,
  privatePractitionersRepresentingContact,
  servedParties,
  user,
}: {
  applicationContext: ServerApplicationContext;
  caseEntity: any;
  docketMeta: any;
  documentType: any;
  newData: any;
  oldData: any;
  privatePractitionersRepresentingContact: any;
  servedParties: any;
  user: any;
  authorizedUser: AuthUser;
}): Promise<{ caseEntity: Case; url: string }> => {
  const partyWithPaperService = caseEntity.hasPartyWithServiceType(
    SERVICE_INDICATOR_TYPES.SI_PAPER,
  );

  const paperServiceRequested =
    partyWithPaperService ||
    user.serviceIndicator === SERVICE_INDICATOR_TYPES.SI_PAPER;

  let shouldCreateWorkItem;

  if (
    user.role === ROLES.irsPractitioner ||
    user.role === ROLES.privatePractitioner
  ) {
    shouldCreateWorkItem = paperServiceRequested;
  } else {
    if (paperServiceRequested || !privatePractitionersRepresentingContact) {
      shouldCreateWorkItem = true;
    }
  }

  applicationContext.logger.info(
    `Starting create Docket entry for change for case ${caseEntity.docketNumber}`,
  );
  const { changeOfAddressDocketEntry, url } = await createDocketEntryForChange({
    applicationContext,
    authorizedUser,
    caseEntity,
    docketMeta,
    documentType,
    newData,
    oldData,
    servedParties,
    user,
  });

  applicationContext.logger.info(
    `Finished create Docket entry for change for case ${caseEntity.docketNumber}`,
  );

  applicationContext.logger.info(
    `Should create work item for case ${caseEntity.docketNumber} ${shouldCreateWorkItem}`,
  );
  if (shouldCreateWorkItem) {
    await createWorkItemForChange({
      applicationContext,
      caseEntity,
      changeOfAddressDocketEntry,
      user,
    });
  }

  applicationContext.logger.info(
    `Starting send served parties emails for case ${caseEntity.docketNumber}`,
  );

  await applicationContext.getUseCaseHelpers().sendServedPartiesEmails({
    applicationContext,
    caseEntity,
    docketEntryId: changeOfAddressDocketEntry.docketEntryId,
    servedParties,
  });

  applicationContext.logger.info(
    `Finished send served parties emails for case ${caseEntity.docketNumber}`,
  );

  return { caseEntity, url };
};
