const { applicationContext } = require('../test/createTestApplicationContext');
const { autoGenerateDeadline } = require('./autoGenerateDeadline');

describe('autoGenerateDeadline', () => {
  it('should set `Served` as the stamp text when the documentType is NOT order and the document eventCode is not one of ENTERED_AND_SERVED_EVENT_CODES', async () => {
    // await autoGenerateDeadline({
    //   applicationContext,
    //   deadlineDate,
    //   description,
    //   subjectCaseEntity,
    // });

    expect(
      applicationContext.getPersistenceGateway().createCaseDeadline.mock
        .calls[0][0].caseDeadline,
    ).toBeDefined();
  });
});
