const {
  applicationContext,
} = require('../../test/createTestApplicationContext');
const {
  COUNTRY_TYPES,
  SERVICE_INDICATOR_TYPES,
} = require('../../entities/EntityConstants');
const { generateChangeOfAddress } = require('./generateChangeOfAddress');
const { MOCK_CASE } = require('../../../test/mockCase');
jest.mock('../addCoversheetInteractor', () => ({
  addCoverToPdf: jest.fn().mockReturnValue({
    pdfData: '',
  }),
}));

describe('generateChangeOfAddress', () => {
  beforeAll(() => {
    const { COUNTRY_TYPES } = applicationContext.getConstants();
    applicationContext.getCurrentUser.mockReturnValue({
      role: 'docketclerk',
      userId: 'docketclerk',
    });
    applicationContext.getPersistenceGateway().getCasesByUser.mockReturnValue([
      {
        ...MOCK_CASE,
        privatePractitioners: [
          {
            barNumber: 'PT5432',
            contact: {
              address1: '234 Main St!',
              address2: 'Apartment 4',
              address3: 'Under the stairs',
              city: 'Chicago',
              countryType: COUNTRY_TYPES.DOMESTIC,
              phone: '+1 (555) 555-5555',
              postalCode: '61234',
              state: 'IL',
            },
            email: 'privatePractitioner1@example.com',
            name: 'Test Private Practitioner',
            representingPrimary: true,
            role: 'privatePractitioner',
            section: 'privatePractitioner',
            serviceIndicator: SERVICE_INDICATOR_TYPES.SI_ELECTRONIC,
            userId: 'ad07b846-8933-4778-9fe2-b5d8ac8ad728',
          },
        ],
        userId: 'abc',
      },
    ]);
  });

  it('attempts to run a change of address when address1 changes', async () => {
    const cases = await generateChangeOfAddress({
      applicationContext,
      contactInfo: {
        address1: '234 Main St',
        address2: 'Apartment 4',
        address3: 'Under the stairs',
        city: 'Chicago',
        countryType: COUNTRY_TYPES.DOMESTIC,
        phone: '+1 (555) 555-5555',
        postalCode: '61234',
        state: 'IL',
      },
      user: {
        barNumber: 'PT5432',
        contact: {
          address1: '234 Main St!',
          address2: 'Apartment 4',
          address3: 'Under the stairs',
          city: 'Chicago',
          countryType: COUNTRY_TYPES.DOMESTIC,
          phone: '+1 (555) 555-5555',
          postalCode: '61234',
          state: 'IL',
        },
        email: 'privatePractitioner1',
        name: 'Test Private Practitioner',
        representingPrimary: true,
        role: 'privatePractitioner',
        section: 'privatePractitioner',
        serviceIndicator: SERVICE_INDICATOR_TYPES.SI_ELECTRONIC,
        userId: 'ad07b846-8933-4778-9fe2-b5d8ac8ad728',
      },
    });

    expect(
      applicationContext.getDocumentGenerators().changeOfAddress,
    ).toHaveBeenCalled();
    expect(cases).toMatchObject([
      expect.objectContaining({ caseId: MOCK_CASE.caseId }),
    ]);
  });

  it('should set isAutoGenerated to true on the generated "Notice of Change of Address" document', async () => {
    applicationContext
      .getUtilities()
      .getDocumentTypeForAddressChange.mockReturnValue({
        eventCode: 'NCA',
        title: 'Notice of Change of Address',
      });

    const cases = await generateChangeOfAddress({
      applicationContext,
      contactInfo: {
        address1: '234 Main St',
        address2: 'Apartment 4',
        address3: 'Under the stairs',
        city: 'Chicago',
        countryType: COUNTRY_TYPES.DOMESTIC,
        phone: '+1 (555) 555-5555',
        postalCode: '61234',
        state: 'IL',
      },
      user: {
        barNumber: 'PT5432',
        contact: {
          address1: '234 Main St!',
          address2: 'Apartment 4',
          address3: 'Under the stairs',
          city: 'Chicago',
          countryType: COUNTRY_TYPES.DOMESTIC,
          phone: '+1 (555) 555-5555',
          postalCode: '61234',
          state: 'IL',
        },
        email: 'privatePractitioner1',
        name: 'Test Private Practitioner',
        representingPrimary: true,
        role: 'privatePractitioner',
        section: 'privatePractitioner',
        serviceIndicator: SERVICE_INDICATOR_TYPES.SI_ELECTRONIC,
        userId: 'ad07b846-8933-4778-9fe2-b5d8ac8ad728',
      },
    });

    const noticeOfChangeOfAddressDocument = cases[0].documents.find(
      d => d.documentType === 'Notice of Change of Address',
    );

    expect(
      applicationContext.getDocumentGenerators().changeOfAddress,
    ).toHaveBeenCalled();
    expect(noticeOfChangeOfAddressDocument).toMatchObject({
      isAutoGenerated: true,
    });
  });
});
