/*
 * dev-ef-cms
 * Documents API for U.S. Tax Court EF-CMS
 *
 * OpenAPI spec version: 2019-03-06T15:30:48Z
 * Contact: webmaster@ustaxcourt.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DevEfCms);
  }
}(this, function(expect, DevEfCms) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CaseDeadline', function() {
      beforeEach(function() {
        instance = new DevEfCms.CaseDeadline();
      });

      it('should create an instance of CaseDeadline', function() {
        // TODO: update the code to test CaseDeadline
        expect(instance).to.be.a(DevEfCms.CaseDeadline);
      });

      it('should have the property createdAt (base name: "createdAt")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property docketNumber (base name: "docketNumber")', function() {
        // TODO: update the code to test the property docketNumber
        expect(instance).to.have.property('docketNumber');
        // expect(instance.docketNumber).to.be(expectedValueLiteral);
      });

      it('should have the property caseDeadlineId (base name: "caseDeadlineId")', function() {
        // TODO: update the code to test the property caseDeadlineId
        expect(instance).to.have.property('caseDeadlineId');
        // expect(instance.caseDeadlineId).to.be(expectedValueLiteral);
      });

      it('should have the property deadlineDate (base name: "deadlineDate")', function() {
        // TODO: update the code to test the property deadlineDate
        expect(instance).to.have.property('deadlineDate');
        // expect(instance.deadlineDate).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

    });
  });

}));
