/*
 * dev-ef-cms
 * Documents API for U.S. Tax Court EF-CMS
 *
 * OpenAPI spec version: 2019-03-06T15:30:48Z
 * Contact: webmaster@ustaxcourt.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DevEfCms);
  }
}(this, function(expect, DevEfCms) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata', function() {
      beforeEach(function() {
        instance = new DevEfCms.CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata();
      });

      it('should create an instance of CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata', function() {
        // TODO: update the code to test CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata
        expect(instance).to.be.a(DevEfCms.CasedocumentsdocketNumbercourtissuedordersdocketEntryIdDocumentMetadata);
      });

      it('should have the property docketNumber (base name: "docketNumber")', function() {
        // TODO: update the code to test the property docketNumber
        expect(instance).to.have.property('docketNumber');
        // expect(instance.docketNumber).to.be(expectedValueLiteral);
      });

      it('should have the property documentTitle (base name: "documentTitle")', function() {
        // TODO: update the code to test the property documentTitle
        expect(instance).to.have.property('documentTitle');
        // expect(instance.documentTitle).to.be(expectedValueLiteral);
      });

      it('should have the property documentType (base name: "documentType")', function() {
        // TODO: update the code to test the property documentType
        expect(instance).to.have.property('documentType');
        // expect(instance.documentType).to.be(expectedValueLiteral);
      });

      it('should have the property draftOrderState (base name: "draftOrderState")', function() {
        // TODO: update the code to test the property draftOrderState
        expect(instance).to.have.property('draftOrderState');
        // expect(instance.draftOrderState).to.be(expectedValueLiteral);
      });

      it('should have the property eventCode (base name: "eventCode")', function() {
        // TODO: update the code to test the property eventCode
        expect(instance).to.have.property('eventCode');
        // expect(instance.eventCode).to.be(expectedValueLiteral);
      });

      it('should have the property richText (base name: "richText")', function() {
        // TODO: update the code to test the property richText
        expect(instance).to.have.property('richText');
        // expect(instance.richText).to.be(expectedValueLiteral);
      });

    });
  });

}));
