import { formatNow } from '@shared/business/utilities/DateHandler';
import { Kysely } from 'kysely';

export async function up(db: Kysely<any>): Promise<void> {
  await db.schema
    .alterTable('dwCase')
    .addColumn('associatedJudge', 'varchar')
    .addColumn('associatedJudgeId', 'varchar')
    .addColumn('automaticBlocked', 'boolean')
    .addColumn('automaticBlockedDate', 'timestamptz')
    .addColumn('automaticBlockedReason', 'varchar')
    .addColumn('blocked', 'boolean')
    .addColumn('blockedDate', 'timestamptz')
    .addColumn('blockedReason', 'varchar')
    .addColumn('caseNote', 'varchar')
    .addColumn('caseType', 'varchar', col => col.defaultTo('').notNull())
    .addColumn('closedDate', 'timestamptz')
    .addColumn('createdAt', 'timestamptz')
    .addColumn('damages', 'numeric')
    .addColumn('filingType', 'varchar')
    .addColumn('hasPendingItems', 'boolean')
    .addColumn('hasVerifiedIrsNotice', 'boolean')
    .addColumn('highPriority', 'boolean')
    .addColumn('highPriorityReason', 'varchar')
    .addColumn('initialCaption', 'varchar')
    .addColumn('initialDocketNumberSuffix', 'varchar')
    .addColumn('irsNoticeDate', 'timestamptz')
    .addColumn('isPaper', 'boolean')
    .addColumn('isSealed', 'boolean')
    .addColumn('litigationCosts', 'numeric')
    .addColumn('mailingDate', 'varchar')
    .addColumn('noticeOfAttachments', 'boolean')
    .addColumn('noticeOfTrialDate', 'timestamptz')
    .addColumn('orderDesignatingPlaceOfTrial', 'boolean')
    .addColumn('orderForAmendedPetition', 'boolean')
    .addColumn('orderForAmendedPetitionAndFilingFee', 'boolean')
    .addColumn('orderForCds', 'boolean')
    .addColumn('orderForFilingFee', 'boolean')
    .addColumn('orderForRatification', 'boolean')
    .addColumn('orderToShowCause', 'boolean')
    .addColumn('partyType', 'varchar', col => col.defaultTo('').notNull())
    .addColumn('petitionPaymentDate', 'timestamptz')
    .addColumn('petitionPaymentMethod', 'varchar')
    .addColumn('petitionPaymentStatus', 'varchar')
    .addColumn('petitionPaymentWaivedDate', 'timestamptz')
    .addColumn('preferredTrialCity', 'varchar')
    .addColumn('procedureType', 'varchar', col => col.defaultTo('').notNull())
    .addColumn('qcCompleteForTrial', 'jsonb')
    .addColumn('receivedAt', 'timestamptz', col =>
      col.defaultTo(formatNow()).notNull(),
    )
    .addColumn('sealedDate', 'timestamptz')
    .addColumn('sortableDocketNumber', 'numeric')
    .addColumn('trialSessionId', 'varchar')
    .addColumn('trialTime', 'varchar')
    .addColumn('useSameAsPrimary', 'boolean')
    .execute();
}

export async function down(db: Kysely<any>): Promise<void> {
  await db.schema
    .alterTable('dwCase')
    .dropColumn('associatedJudge')
    .dropColumn('associatedJudgeId')
    .dropColumn('automaticBlocked')
    .dropColumn('automaticBlockedDate')
    .dropColumn('automaticBlockedReason')
    .dropColumn('blocked')
    .dropColumn('blockedDate')
    .dropColumn('blockedReason')
    .dropColumn('caseNote')
    .dropColumn('caseType')
    .dropColumn('closedDate')
    .dropColumn('createdAt')
    .dropColumn('damages')
    .dropColumn('filingType')
    .dropColumn('hasPendingItems')
    .dropColumn('hasVerifiedIrsNotice')
    .dropColumn('hearings')
    .dropColumn('highPriority')
    .dropColumn('highPriorityReason')
    .dropColumn('initialCaption')
    .dropColumn('initialDocketNumberSuffix')
    .dropColumn('irsNoticeDate')
    .dropColumn('isPaper')
    .dropColumn('isSealed')
    .dropColumn('litigationCosts')
    .dropColumn('mailingDate')
    .dropColumn('noticeOfAttachments')
    .dropColumn('noticeOfTrialDate')
    .dropColumn('orderDesignatingPlaceOfTrial')
    .dropColumn('orderForAmendedPetition')
    .dropColumn('orderForAmendedPetitionAndFilingFee')
    .dropColumn('orderForCds')
    .dropColumn('orderForFilingFee')
    .dropColumn('orderForRatification')
    .dropColumn('orderToShowCause')
    .dropColumn('partyType')
    .dropColumn('petitionPaymentDate')
    .dropColumn('petitionPaymentMethod')
    .dropColumn('petitionPaymentStatus')
    .dropColumn('petitionPaymentWaivedDate')
    .dropColumn('preferredTrialCity')
    .dropColumn('procedureType')
    .dropColumn('qcCompleteForTrial')
    .dropColumn('receivedAt')
    .dropColumn('sealedDate')
    .dropColumn('sortableDocketNumber')
    .dropColumn('trialSessionId')
    .dropColumn('trialTime')
    .dropColumn('useSameAsPrimary')
    .execute();
}
