FROM alpine

RUN apk add --no-cache terraform

# Versions: https://pypi.python.org/pypi/awscli#downloads
ENV AWS_CLI_VERSION 1.15.47

RUN apk --no-cache update && \
    apk --no-cache add python py-pip py-setuptools ca-certificates groff less && \
    pip --no-cache-dir install awscli==${AWS_CLI_VERSION} && \
    rm -rf /var/cache/apk/*

RUN apk add --no-cache bash git openssh

# RUN mkdir -p /home/tomcat

# WORKDIR /data
