FROM alpine

# Versions: https://pypi.python.org/pypi/awscli#downloads
ENV AWS_CLI_VERSION 1.16.31

RUN apk --no-cache update && \
    apk --no-cache add terraform python py-pip py-setuptools ca-certificates groff less && \
    apk --no-cache add bash git openssh && \
    pip --no-cache-dir install awscli==${AWS_CLI_VERSION} && \
    rm -rf /var/cache/apk/*

RUN terraform --version
