#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged
./check-auto-approve.sh

bash_files=$(find . \
    -iname "*.sh" \
    -not -path "./node_modules/*" \
    -not -path "./.husky/**/*.sh")

for file in $bash_files; do
    shellcheck -x -S style $file
done