CREATE USER kswann WITH LOGIN;
GRANT rds_iam TO kswann;
GRANT ALL PRIVILEGES ON DATABASE exp4_dawson TO kswann;
GRANT ALL PRIVILEGES ON SCHEMA public TO kswann;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO kswann;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO kswann;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO kswann;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO kswann;