CREATE USER kswann WITH LOGIN;
GRANT rds_iam TO kswann;
GRANT CONNECT ON DATABASE exp4_dawson TO kswann;
GRANT USAGE ON SCHEMA public TO kswann;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO kswann;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO kswann;
GRANT CREATE ON SCHEMA public TO kswann;
ALTER DEFAULT PRIVILEGES IN SCHEMA public 
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kswann;
ALTER DEFAULT PRIVILEGES IN SCHEMA public 
GRANT USAGE, SELECT ON SEQUENCES TO kswann;


-- super admin privileges
-- CREATE USER kswann WITH LOGIN;
-- GRANT rds_iam TO kswann;
-- GRANT ALL PRIVILEGES ON DATABASE exp4_dawson TO kswann;
-- GRANT ALL PRIVILEGES ON SCHEMA public TO kswann;
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO kswann;
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO kswann;
-- GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO kswann;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO kswann;