name: Node.js CI - API

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '.nvmrc'
      - '.circleci/config.yml'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  API:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/template_no-app.yml
    with:
      run_command: npm run test:api
