# name: Auto-create PRs to test after staging update
# on:
#   pull_request:
#     branches: [staging]
#     types: [closed]

# permissions:
#   pull-requests: write
#   contents: write

# jobs:
#   createPullRequest:
#     if: github.event.pull_request.merged == true
#     timeout-minutes: 2
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           ref: test
#       - name: Reset promotion branch
#         run: |
#           git fetch origin staging:staging
#           git reset --hard staging
#       - name: Create Pull Request
#         id: cpr
#         uses: peter-evans/create-pull-request@v4
#         with:
#           delete-branch: true
#           title: 'Auto backmerge staging into test PR'
#           branch: test-promotion
#           branch-suffix: timestamp
#           body: |
#             Auto backmerge staging into test
#             - Updated with latest staging branch upon feature branch merge
#             - Auto-generated by [create-pull-request][1]

#             [1]: https://github.com/peter-evans/create-pull-request
