name: Build API Typescript

on:
  pull_request:

jobs:
  build_ts_api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Node Dependencies
        run: npm ci
      - name: Build Typescript API
        run: |
          npm run build:assets
          npm run build:lambda:api
