name: Build API Typescript

on:
  pull_request:
  push:
    branches:
      - dependency-updates
      - test

jobs:
  build_ts_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build typescript api
        run: |
          npm ci --legacy-peer-deps
          npm run build:assets
          npm run build:lambda:api
