name: Build API Typescript

on:
  pull_request:
  push:
    branches:
      - dependency-updates

jobs:
  build_ts_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: build typescript api
        run: |
          npm ci
          npm run build:assets
          npm run build:lambda:api
