name: Node.js Client Integration Tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '.nvmrc'
      - '.circleci/config.yml'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  client_integration:
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [12]
        ci_node_index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    uses: ./.github/workflows/template_app-parallel.yml
    with:
      ci_node_index: ${{ matrix.ci_node_index }}
      ci_node_total: ${{ matrix.ci_node_total }}
      configure_sysctl: true
      fetch_depth: 0
      record_jest_test_timings: true
      run_command: |
        export TESTFILES=$(scripts/github-actions/split-tests.ts)
        export JEST_TEST_RESULTS_ARGS="--json --outputFile=${JEST_TEST_RESULTS_FILE}"
        npm run test:client:integration:ci
      upload_logs: true
      workflow_filename: client-integration.yml
  persist-test-file-times:
    needs: [client_integration]
    uses: ./.github/workflows/job_persist-test-file-times.yml
    with:
      workflow_filename: client-integration.yml
