name: E2E Cypress Smoketests Local

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '.nvmrc'
      - '.circleci/config.yml'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e_cypress_smoketests_local:
    uses: ./.github/workflows/template_app.yml
    with:
      configure_sysctl: true
      is_cypress: true
      run_command: |
        npm run cypress:smoketests:local
      workflow_filename: e2e-cypress-public.yml
