name: E2E Cypress Public

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '.nvmrc'
      - '.circleci/config.yml'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e_cypress_public:
    runs-on: ubuntu-latest

    env:
      CI: true
      CHECK_DEPLOY_DATE_INTERVAL: 5000
    services:
      postgres:
        image: postgres:17.9-trixie
        env:
          POSTGRES_PASSWORD: example
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - name: Setup OpenSearch
        uses: ankane/setup-opensearch@v1
        with:
          opensearch-version: 3.5.0
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v2
        with:
          comment_on_pr: false
      - name: Restore Cache Dependencies
        id: cache-dependencies
        uses: actions/cache/restore@v5
        with:
          path: |
            node_modules
            .cache/puppeteer
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Node Dependencies - Cache Miss Install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        id: npm-clean-install
        run: npm ci
      - name: Setup Postgres
        run: |
          npm run migration:postgres
          npm run migration:postgres:contract
          npm run seed:postgres
      - name: Run E2E Cypress
        run: |
          mkdir -p /tmp/cypress/
          npm run start:all:ci >> /tmp/cypress/cypress-output.txt &
          ./wait-until-services.sh
          sleep 5
          npm run cypress:integration:public
      - name: Store Cypress Failure Videos
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: cypress-videos
          path: ${{ github.workspace }}/cypress/local-only/videos
      - name: Save Cache Dependencies
        if: steps.npm-clean-install.outcome == 'success'
        uses: actions/cache/save@v5
        with:
          path: |
            node_modules
            .cache/puppeteer
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
