name: E2E Pa11y

on:
  pull_request:

jobs:
  e2e_pa11y:
    runs-on: ubuntu-latest

    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.10.2
          security-enabled: false
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v3.0.0
        with:
          port: 8000
          cors: '*'
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
        with:
          comment_on_pr: false
      - name: Install Node Dependencies
        run: npm ci
      - name: Start API and Client
        run: |
          mkdir -p /tmp/pa11y/
          npm run start:all:ci >> /tmp/pa11y/pa11y-server.txt &
          URL=http://localhost:1234 ./wait-until.sh
          sleep 20
      - name: Run E2E Pa11y 1
        run: npm run test:pa11y:1 --node-flags --max-old-space-size=1024
      - name: Run E2E Pa11y 2
        run: npm run test:pa11y:2 --node-flags --max-old-space-size=1024
      - name: Run E2E Pa11y 3
        run: npm run test:pa11y:3 --node-flags --max-old-space-size=1024
      - name: Run E2E Pa11y 4
        run: npm run test:pa11y:4 --node-flags --max-old-space-size=1024
      - name: Store Screenshots Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: screen-shots
          path: ${{ github.workspace }}/web-client/pa11y/pa11y-screenshots
      - name: Store Server Logs
        uses: actions/upload-artifact@v3
        with:
          name: server-logs
          path: /tmp/pa11y
