name: E2E Cypress Public

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '.nvmrc'
      - '.circleci/config.yml'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e_cypress_public:
    uses: ./.github/workflows/template_app.yml
    with:
      check_deploy_date_interval: '5000'
      is_cypress: true
      run_command: |
        npm run cypress:integration:public
      workflow_filename: e2e-cypress-public.yml
