name: E2E Cypress Public

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '.nvmrc'
      - '.circleci/config.yml'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e_cypress_public:
    uses: ./.github/workflows/templates/app.yml
    with:
      check_deploy_date_interval: '5000'
      extra_artifact_if_always: true
      extra_artifact_name: cypress-videos
      extra_artifact_path: ${{ github.workspace }}/cypress/local-only/videos
      run_command: |
        npm run migration:postgres
        npm run migration:postgres:contract
        npm run seed:postgres
        mkdir -p /tmp/cypress/
        npm run start:all:ci >> /tmp/cypress/cypress-output.txt &
        WAIT_FOR_PUBLIC=1 ./wait-until-services.sh
        npm run cypress:integration:public
