name: E2E Pa11y

on:
  pull_request:

jobs:
  e2e_pa11y:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [4]
        ci_node_index: [1, 2, 3, 4]
    env:
      CI: true
      CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
      CI_NODE_INDEX: ${{ matrix.ci_node_index }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.12.0'
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.10.2
          security-enabled: false
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v4.0.0
        with:
          port: 8000
          cors: '*'
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v2
        with:
          comment_on_pr: false
      - name: Install Node Dependencies
        run: npm ci
      - name: Start API and Client
        run: |
          mkdir -p /tmp/pa11y/
          npm run start:all:ci >> /tmp/pa11y/pa11y-server.txt &
          URL=http://localhost:1234 ./wait-until.sh
          sleep 20
      - name: Run E2E Pa11y
        run: npm run test:pa11y:${{ matrix.ci_node_index }} --node-flags --max-old-space-size=1024
      # - name: Run E2E Pa11y 2
      #   run: npm run test:pa11y:2 --node-flags --max-old-space-size=1024
      # - name: Run E2E Pa11y 3
      #   run: npm run test:pa11y:3 --node-flags --max-old-space-size=1024
      # - name: Run E2E Pa11y 4
      #   run: npm run test:pa11y:4 --node-flags --max-old-space-size=1024
      - name: Store Server Logs
        uses: actions/upload-artifact@v4
        with:
          name: server-logs-${{ matrix.ci_node_index }}
          path: /tmp/pa11y
