name: E2E Cypress Smoketests Local

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '.nvmrc'
      - '.circleci/config.yml'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e_cypress_smoketests_local:
    uses: ./.github/workflows/template_app.yml
    with:
      configure_sysctl: true
      extra_artifact_if_always: true
      extra_artifact_name: cypress-videos
      extra_artifact_path: ${{ github.workspace }}/cypress/deployed-and-local/videos
      extra_artifact_two_name: cypress-logs
      extra_artifact_two_path: /tmp/cypress
      run_command: |
        npm run migration:postgres
        npm run migration:postgres:contract
        npm run seed:postgres
        mkdir -p /tmp/cypress/
        npm run start:all:ci >> /tmp/cypress/cypress-output.txt &
        ./wait-until-services.sh
        sleep 5
        npm run cypress:smoketests:local
