name: E2E Cypress Accessibility

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '.nvmrc'
      - '.circleci/config.yml'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  e2e_cypress_accessibility:
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [6]
        ci_node_index: [0, 1, 2, 3, 4, 5]
    uses: ./.github/workflows/templates/app-parallel.yml
    with:
      ci_environment: 'true'
      ci_node_index: ${{ matrix.ci_node_index }}
      ci_node_total: ${{ matrix.ci_node_total }}
      fetch_depth: 0
      run_command: |
        npm run migration:postgres
        npm run migration:postgres:contract
        npm run seed:postgres
        mkdir -p /tmp/test-file-times
        mkdir -p /tmp/cypress/
        npm run start:all:ci >> /tmp/cypress/cypress-output.txt &
        WAIT_FOR_CLIENT=1 WAIT_FOR_PUBLIC=1 ./wait-until-services.sh
        export TESTFILES=$(scripts/github-actions/split-tests-cypress.ts accessibility)
        scripts/github-actions/run-cypress-tests-with-timing.ts cypress.config.ts "$TESTFILES" "$TEST_FILE_TIMINGS_SHARD_FILE"
      workflow_filename: e2e-cypress-accessibility.yml
  persist-test-file-times:
    needs: [e2e_cypress_accessibility]
    uses: ./.github/workflows/shared/persist-test-file-times.yml
    with:
      workflow_filename: e2e-cypress-accessibility.yml
