name: E2E Cypress

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '.nvmrc'
      - '.circleci/config.yml'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  e2e_cypress:
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [12]
        ci_node_index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    uses: ./.github/workflows/template_app-parallel.yml
    with:
      ci_environment: 'true'
      ci_node_index: ${{ matrix.ci_node_index }}
      ci_node_total: ${{ matrix.ci_node_total }}
      fetch_depth: 0
      is_cypress: true
      run_command: |
        export TESTFILES=$(scripts/github-actions/split-tests-cypress.ts integration)
        scripts/github-actions/run-cypress-tests-with-timing.ts cypress.config.ts "$TESTFILES" "$TEST_FILE_TIMINGS_SHARD_FILE"
      workflow_filename: e2e-cypress.yml
  persist-test-file-times:
    needs: [e2e_cypress]
    uses: ./.github/workflows/job_persist-test-file-times.yml
    with:
      workflow_filename: e2e-cypress.yml
