name: Check Coverage

on:
  workflow_call:
    inputs:
      branches:
        required: true
        type: number
      functions:
        required: true
        type: number
      lines:
        required: true
        type: number
      statements:
        required: true
        type: number
      workflow_filename:
        required: true
        type: string

permissions:
  actions: read
  contents: read

jobs:
  check-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v6
      - name: Download Coverage Artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: ${{ inputs.workflow_filename }}-coverage-artifacts-*
          merge-multiple: true
          path: coverage
      - name: Process Coverage
        run: |
          npx nyc report \
            --check-coverage \
            --branches ${{ inputs.branches }} \
            --functions ${{ inputs.functions }} \
            --lines ${{ inputs.lines }} \
            --statements ${{ inputs.statements }} \
            --reporter lcov \
            --reporter text \
            --reporter clover \
            -t coverage
      - name: Delete Coverage Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: coverage-artifacts
          failOnError: false
