name: Node.js CI - Lint

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '.nvmrc'
      - '.circleci/config.yml'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Lint:
    uses: ./.github/workflows/templates/no-app.yml
    with:
      run_command: |
        npm run lint
        ./run-shellcheck.sh
