name: Node.js CI - Scripts

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '.nvmrc'
      - '.circleci/config.yml'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  Scripts:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/template_no-app.yml
    with:
      run_command: npm run test:scripts
  check-coverage:
    needs: [Scripts]
    uses: ./.github/workflows/job_check-coverage.yml
    with:
      branches: 97
      coverage_source_dir: scripts/coverage
      coverage_suite: scripts
      functions: 99
      lines: 99
      pull_request_number: ${{ github.event.pull_request.number }}
      statements: 99
      workflow_filename: scripts.yml
  update-coverage-table:
    if: ${{ github.event.pull_request.base.ref == 'prod' }}
    needs: [check-coverage]
    runs-on: ubuntu-latest
    env:
      COMPOSITE_COVERAGE_SUMMARY_PATH: /tmp/scripts-pr-${{ github.event.pull_request.number }}-coverage-summary.json
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v6
      - name: NPM Install in Current Branch
        uses: ./.github/actions/dawson-node-bootstrap
      - name: Download composite coverage summary
        uses: actions/download-artifact@v7
        with:
          name: coverage-summary-scripts-pr-${{ github.event.pull_request.number }}
          path: /tmp
      - name: Update coverage table
        run: |
          scripts/github-actions/update-prod-release-coverage.ts \
            "${COMPOSITE_COVERAGE_SUMMARY_PATH}" \
            ${{ github.event.pull_request.number }}
