name: Node.js CI - Scripts

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '.nvmrc'
      - '.circleci/config.yml'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Scripts:
    uses: ./.github/workflows/template_no-app.yml
    with:
      run_command: npm run test:scripts
