name: Node.js CI - Shared

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '.nvmrc'
      - '.circleci/config.yml'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  Shared:
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [2]
        ci_node_index: [0, 1]
    uses: ./.github/workflows/template_no-app-parallel.yml
    with:
      ci_node_index: ${{ matrix.ci_node_index }}
      ci_node_total: ${{ matrix.ci_node_total }}
      coverage_source_dir: shared/coverage/${{ matrix.ci_node_index }}
      fetch_depth: 0
      splitter_command: scripts/github-actions/split-tests-glob.ts -shared
      test_command: NODE_INDEX=${{ matrix.ci_node_index }} npm run test:shared:ci
      workflow_filename: shared.yml
  check-coverage:
    needs: [Shared]
    uses: ./.github/workflows/job_check-coverage.yml
    with:
      branches: 95
      functions: 95
      lines: 95
      statements: 95
      workflow_filename: shared.yml
  persist-test-file-times:
    needs: [Shared]
    uses: ./.github/workflows/job_persist-test-file-times.yml
    with:
      workflow_filename: shared.yml
