name: Node.js CI - Shared

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '.nvmrc'
      - '.circleci/config.yml'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Shared:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [4]
        ci_node_index: [0, 1, 2, 3]
    env:
      CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
      CI_NODE_INDEX: ${{ matrix.ci_node_index }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v2
        with:
          comment_on_pr: false
      - name: Restore Cache Dependencies
        id: cache-dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            .cache/puppeteer
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Node Dependencies - Cache Miss Install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        id: npm-clean-install
        run: npm ci
      - name: Shared
        run: |
          export TESTFILES=$(npx ts-node split-tests-glob.ts -shared)
          NODE_INDEX=${{ matrix.ci_node_index }} npm run test:shared:ci
      - name: Rename coverage to shard coverage
        run: |
          mkdir -p coverage
          cp shared/coverage/${{ matrix.ci_node_index }}/lcov.info coverage/lcov-${{ matrix.ci_node_index }}.info
          cp shared/coverage/${{ matrix.ci_node_index }}/coverage-final.json coverage/coverage-${{ matrix.ci_node_index }}.json
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts-${{ matrix.ci_node_index }}
          path: coverage
      - name: Save Cache Dependencies
        if: steps.npm-clean-install.outcome == 'success'
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
            .cache/puppeteer
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
  check-coverage:
    runs-on: ubuntu-latest
    needs: [Shared]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: coverage-artifacts-*
          merge-multiple: true
          path: coverage
      - name: Process Coverage
        run: npx nyc report --check-coverage --branches 95 --functions 95 --lines 95 --statements 95 --reporter lcov --reporter text --reporter clover -t coverage
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: coverage-artifacts
          failOnError: false
