name: GitHub Actions Workflow Template - DAWSON not running, with parallelization

on:
  workflow_call:
    inputs:
      ci_node_index:
        required: true
        type: number
      ci_node_total:
        required: true
        type: number
      coverage_source_dir:
        required: true
        type: string
      fetch_depth:
        default: 0
        type: number
      splitter_command:
        required: true
        type: string
      test_command:
        required: true
        type: string
      workflow_filename:
        required: true
        type: string

permissions:
  actions: read
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      CI_NODE_TOTAL: ${{ inputs.ci_node_total }}
      CI_NODE_INDEX: ${{ inputs.ci_node_index }}
      JEST_TEST_RESULTS_FILE: /tmp/test-file-times/jest-results-${{ inputs.ci_node_index }}.json
      TEST_FILE_TIMINGS_PATH: /tmp/test-file-times/${{ inputs.workflow_filename }}-historical-test-file-times.json
      TEST_FILE_TIMINGS_SHARD_FILE: /tmp/test-file-times/${{ inputs.workflow_filename }}-historical-test-file-times-shard-${{ inputs.ci_node_index }}.json
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v6
        with:
          fetch-depth: ${{ inputs.fetch_depth }}
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v2
        with:
          comment_on_pr: false
      - name: NPM Install in Current Branch
        uses: ./.github/actions/dawson-node-bootstrap
      - name: Restore historical test file timings
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          scripts/github-actions/download-historical-test-file-times.ts ${{ inputs.workflow_filename }} historical-test-file-times $TEST_FILE_TIMINGS_PATH
      - name: Run tests
        run: |
          mkdir -p /tmp/test-file-times
          export TESTFILES=$(${{ inputs.splitter_command }})
          export JEST_TEST_RESULTS_ARGS="--json --outputFile=${JEST_TEST_RESULTS_FILE}"
          ${{ inputs.test_command }}
      - name: Record shard test file timings
        if: success()
        run: |
          if [[ -f "${JEST_TEST_RESULTS_FILE}" ]]; then
            scripts/github-actions/test-file-times.ts from-jest "${JEST_TEST_RESULTS_FILE}" "${TEST_FILE_TIMINGS_SHARD_FILE}"
          fi
      - name: Rename coverage to shard coverage
        run: |
          mkdir -p coverage
          cp "${{ inputs.coverage_source_dir }}/lcov.info" "coverage/lcov-${{ inputs.ci_node_index }}.info"
          cp "${{ inputs.coverage_source_dir }}/coverage-final.json" "coverage/coverage-${{ inputs.ci_node_index }}.json"
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.workflow_filename }}-coverage-artifacts-${{ inputs.ci_node_index }}
          path: coverage
      - name: Upload historical test file timings
        uses: actions/upload-artifact@v7
        if: success()
        with:
          if-no-files-found: ignore
          name: ${{ inputs.workflow_filename }}-historical-test-file-times-shard-${{ inputs.ci_node_index }}
          path: ${{ env.TEST_FILE_TIMINGS_SHARD_FILE }}
