name: Typescript File Check

on:
  pull_request:

jobs:
  CheckAllFilesForTypeErrorCount:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Target Branch
        id: target_branch
        run: |
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          TARGET_BRANCH=$(jq -r '.pull_request.base.ref' $GITHUB_EVENT_PATH)
          echo "TARGET_BRANCH: $TARGET_BRANCH"
          echo "TARGET_BRANCH=$TARGET_BRANCH" >> $GITHUB_ENV

      - name: Checkout Target Branch
        uses: actions/checkout@v4
        with:
          repository: ustaxcourt/ef-cms
          ref: ${{ env.TARGET_BRANCH }}
          path: targetBranch

      - uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'

      - name: NPM Install in your branch
        run: npm ci

      - name: NPM Install in target branch
        working-directory: ./targetBranch
        run: npm ci

      - name: Check untouched files
        run: npx ts-node scripts/checkAllFilesForTypeErrorCount.ts
