name: Typescript Reduce Type Errors

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '.nvmrc'
      - '.circleci/config.yml'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ReduceTypeErrors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout USTC Staging
        uses: actions/checkout@v6
        with:
          repository: ustaxcourt/ef-cms
          ref: staging
          path: stagingBranch
      - name: Checkout Current Branch
        uses: actions/checkout@v6
        with:
          path: branchToBeCompared
      - name: NPM Install in Current Branch
        uses: ./.github/actions/dawson-node-bootstrap
        with:
          node-version-file: branchToBeCompared/.nvmrc
          restore-cache: 'false'
          save-cache: 'false'
          working-directory: ./branchToBeCompared
      - name: NPM Install in USTC Staging
        uses: ./.github/actions/dawson-node-bootstrap
        with:
          restore-cache: 'false'
          save-cache: 'false'
          setup-node: 'false'
          working-directory: ./stagingBranch
      - name: Compare errors between your branch and staging
        working-directory: ./branchToBeCompared
        run: npx ts-node scripts/compareTypescriptErrors.ts
